### PR TITLE
WIP: global: change the static url path

### PR DESCRIPTION
**Pull request by drjova**
* Changes the ``static_url_path`` from ``/static`` to ``/assets`` to
  help us move to the new UI infrastructure.

Signed-off-by: Harris Tzovanakis <me@drjova.com>

### CODE REVIEW

**Comment by drjova** [comment]
First merge: https://github.com/inspirehep/inspirehep-search-js/pull/91

**Comment by david-caro** [comment]
Hmm... couldn't we separate the new ui/old ui by a more meaningful url? (something like `/newui/static`, `/react/static` or something similar).
Changing it only for the new ui part minimizes the risk on the current ui too.

**Comment by harunurhan** [comment]
@david-caro 

Somehow we don't have a control over the path of static files that are created after building the react app. Unfortunately it's not configurable and it has a lot of references to it from other compiled, minified js files and html. So your solution only possible if we serve whole react app under a different url like `newui` or `react`, then all links inside the app will have to be prefixed too which is not good.

**Comment by david-caro** [comment]
okok :/, ugly stuff. So maybe then changing `assets` for `oldui` or `flask`. The idea is to make it clear by the name that you are going to a different backend (one is flask, the other react).

**Comment by drjova** [comment]
hmm ``oldui`` or ``flask`` for static files is a bit weird though :/ I'd go for ``flask``

**Comment by david-caro** [comment]
naming is one of the oldest computer science unsolved problem xd

**Comment by drjova** [comment]
true 📟

**Comment by drjova** [comment]
Supersede by https://github.com/inspirehep/inspire-next/pull/3563

**Pull request closed without merging**
