### PR TITLE
e2e: add first e2e test for arxiv harvest

### PR DESCRIPTION
**Pull request by ammirate**
This commit adds a new test suite called e2e in our docker
environment, which spins up all the containers needed for e2e tests.
A `fake-arxiv-service` class is added and instantiated in a new container
in the e2e tests.
Furthermore, a new end-to-end test for harvesting a core article from arxiv
has beeen added.
Legacy and RT services are not mocked and bypassed by the
`PRODUCTION-MODE` feature flag.

Signed-off-by: Antonio Cesarano <cesarano2607@gmail.com>

## Checklist:

- [x] I have all the information that I need (if not, move to `RFC` and look for it).
- [x] I linked the related issue(s) in the corresponding commit logs.
- [x] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [x] My code follows the code style of this project.
- [x] I've added any new docs if API/utils methods were added.
- [x] I have updated the existing documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ammirate** [comment]
ci test please unit

**Comment by david-caro** [comment]
ci dcaro_tests please

**Comment by david-caro** [comment]
ci dcaro_tests please

**Comment by david-caro** [comment]
ci dcaro_tests please

**Comment by david-caro** [comment]
ci dcaro_tests please

**Comment by david-caro** [comment]
ci dcaro_tests please

**Comment by david-caro** [comment]
ci dcaro_tests please

**Comment by david-caro** [comment]
ci dcaro_tests please

**Comment by david-caro** [comment]
ci dcaro_tests please

**Comment by david-caro** [comment]
ci dcaro_tests please

**Comment by david-caro** [comment]
ci dcaro_tests please

**Comment by david-caro** [comment]
ci dcaro_tests please

**Comment by david-caro** [comment]
ci dcaro_tests please

**Comment by david-caro** [comment]
ci dcaro_tests please

**Comment by david-caro** [comment]
ci dcaro_tests please

**Comment by david-caro** [comment]
ci test please

**Comment by ammirate** [comment]
ci test please e2e

**Comment by ammirate** [comment]
run my tests for the love of Zeus

**Comment by david-caro** [comment]
I misled you, sorry, you have to add e2e, like "run the e2e for the love of Merriam Webster!"

**Comment by ammirate** [comment]
run the e2e for the love of teletubbies

**Comment by ammirate** [comment]
run the e2e for the love of Jenkins

**Comment by ammirate** [comment]
run the e2e for the love of David

**Comment by ammirate** [comment]
run the e2e for the love of JuJitsu

**Comment by ammirate** [comment]
run the e2e for the love of somebody

**Comment by ammirate** [comment]
run the e2e for the love of MotherBoard

**Comment by ammirate** [comment]
run the e2e for the love of Inspire

**Comment by ammirate** [comment]
run the e2e test for the love of Moira Orfei

**Comment by ammirate** [comment]
run the e2e for the love of Moira Orfei

**Comment by ammirate** [comment]
run the e2e for the love of Son Goku

**Comment by ammirate** [comment]
run the e2e for the love of Camillo Benso

**Comment by ammirate** [comment]
run the e2e for the love of Ducati

**Comment by ammirate** [comment]
run the e2e for the love of EasyJet

**Comment by ammirate** [comment]
run the e2e for the love of EasyJet2

**Comment by ammirate** [comment]
run the e2e for the love of Iuliana

**Comment by iulianav** [comment]
run the e2e for the love of avoiding regressions

**Comment by ammirate** [comment]
run the e2e for the love of Kubernetes

**Comment by ammirate** [comment]
run the e2e for the love of Pods

**Comment by ammirate** [comment]
run the e2e for the love of Ruada

**Comment by ammirate** [comment]
run the e2e for the love of Terminator

**Comment by ammirate** [comment]
run the e2e for the love of the Gioconda

**Comment by ammirate** [comment]
run the e2e for the love of the lost Harris

**Comment by ammirate** [comment]
run the e2e for the love of whatever

**Comment by ammirate** [comment]
run the e2e for the love of ErgoDox

**Comment by ammirate** [comment]
run the e2e for the love of bash

**Comment by ammirate** [comment]
run the e2e for the love of json

**Comment by ammirate** [comment]
run the e2e for the love of coffee

**Comment by ammirate** [comment]
run the e2e for the love of Git

**Comment by ammirate** [comment]
run the e2e for the love of reflog command

**Comment by ammirate** [comment]
run the e2e for the love of reflog command

**Comment by ammirate** [comment]
run the e2e for the love of Jenkins

**Comment by ammirate** [comment]
run the e2e for the love of Ricore`

**Comment by ammirate** [comment]
run the e2e for the love of Freedom

**Comment by ammirate** [comment]
run the e2e for the love of Pinocchio

**Comment by ammirate** [comment]
run the e2e for the love of PAMPALEONE

**Comment by ammirate** [comment]
run the e2e for the love of Linsoft

**Comment by ammirate** [comment]
run the e2e for the love of CocaCola

**Comment by ammirate** [comment]
run the e2e for the love of Twinings

**Comment by ammirate** [comment]
run the e2e for the love of Dolores

**Comment by ammirate** [comment]
run the e2e for the love of Sauron

**Comment by ammirate** [comment]
run the e2e for the love of the lion king

**Comment by ammirate** [comment]
run the e2e for the love of Tizio, Caio, and Sempronio

**Comment by ammirate** [comment]
run the e2e for the love of Staedtler

**Comment by ammirate** [comment]
run the e2e for the love of Harun

**Comment by ammirate** [comment]
run the e2e for the love of chihuahua

**Comment by ammirate** [comment]
run the e2e for the love of Pizza

**Comment by ammirate** [comment]
run the e2e for the love of Niagara

**Comment by ammirate** [comment]
run the e2e for the love of Nutella

**Comment by ammirate** [comment]
run the e2e for the love of Crepes

**Comment by ammirate** [comment]
run the e2e for the love of retrospectives

**Comment by ammirate** [comment]
run the e2e for the love of arXiv

**Comment by ammirate** [comment]
run the e2e for the love of Football

**Comment by ammirate** [comment]
run the e2e for the love of Gregorian

**Comment by ammirate** [comment]
run the e2e for the love of broken passwords

**Comment by ammirate** [comment]
run the e2e for the love of  Vlad Tepes

**Comment by ammirate** [comment]
run the e2e for the love of boiled eggs

**Comment by ammirate** [comment]
run the e2e for the love of Vim

**Comment by ammirate** [comment]
run the e2e for the love of tax delcaration

**Comment by ammirate** [comment]
run the e2e for the love of Nefertiti

**Comment by ammirate** [comment]
run the e2e for the love of Monday

**Comment by ammirate** [comment]
run the e2e for the love of biking

**Comment by ammirate** [comment]
run the e2e for the love of people who think to other places

**Comment by ammirate** [comment]
run the e2e for the love of distracted people

**Comment by ammirate** [comment]
run the e2e for the love of Bixby

**Comment by ammirate** [comment]
run the e2e for the love of COFT

**Comment by ammirate** [comment]
run the e2e for the love of the spanish inquisition

**Comment by ammirate** [comment]
run the e2e for the love of Celery 4

**Comment by ammirate** [comment]
run the e2e for the love of broken credit cards

**Comment by ammirate** [comment]
run the e2e for the love misconfigured services

**Comment by ammirate** [comment]
run the e2e for the love misconfigured services

**Comment by ammirate** [comment]
run the e2e for the love of leather jackets

**Comment by ammirate** [comment]
run the e2e for the love of videocourses

**Comment by ammirate** [comment]
run the e2e for the love of another coffee needed

**Comment by ammirate** [comment]
run the e2e for the love of expensive envelopes for tax declarations

**Comment by ammirate** [comment]
run the e2e for the love of blabla

**Comment by ammirate** [comment]
run the e2e for the love of blablablaaaaaaaaaaa

**Comment by ammirate** [comment]
run the e2e for the love of npm failing

**Comment by ammirate** [comment]
run the e2e for the love of non cleaning up containers

**Comment by ammirate** [comment]
run the e2e for the love of politeness

**Comment by ammirate** [comment]
run the e2e for the love of the first success!

**Comment by david-caro** [comment]
run the e2e for the love of my wallet!

**Comment by david-caro** [comment]
run the e2e for the love of 70 euros lost

**Comment by david-caro** [comment]
run the e2e for the love of indentation

**Comment by david-caro** [comment]
ci test please

**Comment by david-caro** [comment]
ci test please

**Comment by david-caro** [comment]
ci merge please

**Pull request merged**
