### PR TITLE
config: make records visible without authorization

### LINKED ISSUE #1285: records are under authorization
Records are currently not accessible without authorization.

I assume this might be happening after https://github.com/inspirehep/inspire-next/commit/668309951dfca65cab3bbf09e76f804203ef7188 was introduced.

By adding some permissions to a user, it might be that guests now cannot access records as `invenio-access` allows everybody to do all actions until the action is assigned to some user.

This needs to be checked.

### PR DESCRIPTION
**Pull request by jacquerie**
Closes #1285

### CODE REVIEW

**Comment by jacquerie** [comment]
Pinging @Panos512 to show him the changes needed in the ORCID User fixture.

**Comment by jacquerie** [comment]
Maybe @jmartinm has some time to look at this?

**Comment by jmartinm** [comment]
> Ready for review. Maybe @jmartinm has some time to look at this?

It works as intended as far as I can see.

**Comment by kaplun** [comment]
Awesome!

**Comment by kaplun** [comment]
Shall we merge this one? Can you just rebase it once more?

**Comment by kaplun** [comment]
What happened to Travis?

**Comment by jacquerie** [comment]
All machines were busy because of https://travis-ci.org/inspirehep/inspire-next/builds/146360877 and https://travis-ci.org/inspirehep/inspire-next/builds/146368774, which took a lot and achieved nothing...

**Comment by kaplun** [comment]
Are you trying to tell me something? :stuck_out_tongue_closed_eyes:

**Comment by jacquerie** [comment]
Ah, no, I'm not saying it's your fault! But we should do something, either by fixing the tests or taking the shortcut of disabling the build.

**Pull request merged**
