### PR TITLE
timeout for the es_bulk request doubled

### PR DESCRIPTION
**Pull request by rikirenz**
With the mac OS docker seems to require more time to processed all the data in the elastic search. 
I think on other OS works properly.

### CODE REVIEW

**Comment by jmartinm** [comment]
If it is a problem within Docker, shall we add it https://github.com/inspirehep/inspire-next/blob/master/docker-compose.yml#L37 instead?

**Comment by rikirenz** [comment]
Ok, it makes sense. I will try to modify it.

**Comment by kaplun** [comment]
@rikirenz can you rebase your branch against latest master and repush it? Also you can squash your last commit into the main one.

For bot you can use `git rebase master -i`

**Comment by jmartinm** [comment]
This ready to be merged it seems?

**Comment by jmartinm** [comment]
@rikirenz please rebase with master and comment on this PR so that this can be merged.

**Comment by rikirenz** [comment]
I have pushed. I think is ready to be merged

**Pull request merged**
