### PR TITLE
docker: use sane locale vars

### PR DESCRIPTION
**Pull request by david-caro**
- [x] I have all the information that I need (if not, move to `RFC` and look for it).
- [ ] I linked the related issue(s) in the corresponding commit logs.
- [x] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [x] My code follows the code style of this project.
- [ ] I've added any new docs if API/utils methods were added.
- [ ] I have updated the existing documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Signed-off-by: David Caro <david@dcaro.es>

### CODE REVIEW

**Comment by david-caro** [comment]
Thanks a lot @michamos !
@zzacharo this solves the utf-8 issues you were having.

**Comment by michamos** [comment]
shouldn't this be the same as on production?
```
02:12 pm env:inspire_production_to_deploy ~ 
mimoskov@inspire-prod-worker3-build1$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=

```

**Comment by david-caro** [comment]
Did you try running locale after `sudo -i` ? I think it's getting your user's locale instead:

```
02:24 PM env:inspire_production_to_deploy ~ 
root@inspire-prod-worker3-build1$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by david-caro** [comment]
Dammit... I think sudo/ssh just reuse whatever you were using on your client Xd

**Comment by jacquerie** [comment]
...although probably `LANG=en_US.UTF-8` would be enough.

**Comment by david-caro** [comment]
Actually, I tried and that one was not enough, I had to enable at least the LC_MESSAGES iirc

**Pull request merged**
