### PR TITLE
schemas: make australia part of australasia

### PR DESCRIPTION
**Pull request by jacquerie**
As per https://github.com/inspirehep/inspire/issues/199#issuecomment-239185808.

### CODE REVIEW

**Comment by kaplun** [comment]
@inspirehep/inspire-content Can't we have this occasion to simply improve the model to ask for supporting a specific location? (possibly up to a (list of) full addresses - and corresponding geocoding coordinates)?

Then the region can be simply derived from it. In this way we would be consistent with the Conference and Insittution database and we could place jobs right on the map.

**Comment by jacquerie** [comment]
This would be cool, but we haven't generally solved the problem of integrating a geocoding solution in INSPIRE, so I believe that it can be pushed back...

**Comment by kaplun** [comment]
Pushed back by whom? In principle we can happily use Google APIs since we are not receiving more than a handful of conference entries per month :)

What I am proposing here is simply to prepare the schema to welcome a list of addresses and corresponding geocoding to be ready for when we introduce forms to let user select such pieces of info.

But yep this is the subject of a new Github issue.

**Comment by kaplun** [comment]
LGTM

**Pull request merged**
