### PR TITLE
config: consolidate usage of dicts and rest endpoints

### PR DESCRIPTION
**Pull request by david-caro**
- [x] I have all the information that I need (if not, move to `RFC` and look for it).
- [x] I linked the related issue(s) in the corresponding commit logs.
- [x] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [x] My code follows the code style of this project.
- [x] I've added any new docs if API/utils methods were added.
- [x] I have updated the existing documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Signed-off-by: David Caro <david@dcaro.es>

### CODE REVIEW

**Comment by david-caro** [comment]
ci test please

**Comment by drjova** [comment]
I just realized how many ``_db`` we have which is useless :(

**Comment by david-caro** [comment]
> I just realized how many _db we have which is useless :(

yep... I did a first try to have a function to generate them from the  non-db ones, but there seems to be no pattern we can reuse on all of them.

**Comment by david-caro** [comment]
But anyhow, I think that they should end up disappearing, and becoming the default ones.

**Comment by david-caro** [comment]
ci merge please

**Comment by david-caro** [comment]
ci merge please

**Comment by ammirate** [comment]
ci merge please

**Pull request merged**
