### PR TITLE
workflow: preserve references

### PR DESCRIPTION
**Pull request by kaplun**
- [x] I have all the information that I need (if not, move to `RFC` and look for it).
- [x] I linked the related issue(s) in the corresponding commit logs.
- [x] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [x] My code follows the code style of this project.
- [x] I've added any new docs if API/utils methods were added.
- [x] I have updated the existing documentation accordingly.
- [x] *I have removed tests that covered the removed feature.*
- [ ] All new and existing tests passed.

* Now that refextract is using fresh journal information there's
  no more need to drop references before sending them to legacy.

Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by michamos** [comment]
If I understand correctly, this means that there are no record ids in the references, and that we let bibrank dynamically match records until we have a reference matcher on labs. Is that OK?

**Comment by kaplun** [comment]
So... I believe it is, because:
* IDs would be added nevertheless when exporting back records to labs via prodsync.
* For the final user, there's no practical difference between IDs guessed by bibrank or IDs guessed by refextract.

**Comment by david-caro** [comment]
Don't we have any tests that check if the references are extracted?

**Comment by jacquerie** [comment]
> Don't we have any tests that check if the references are extracted?

We do: https://github.com/inspirehep/inspire-next/blob/7fad81f08139c9b5f726a361e52128e577f28bfe/tests/unit/workflows/test_workflows_tasks_refextract.py#L96-L105

**Pull request closed without merging**
