### PR TITLE
[WIP] format: Job detailed record

### PR DESCRIPTION
**Pull request by nikpap**
- [x] Check all JSON fields
- https://github.com/inspirehep/inspire-next/blob/invenio3/inspirehep/modules/records/jsonschemas/records/jobs.json
- [x] Closing soon button
- [x] Applications box
- [x] Fix date format
- [x] Add map(?)

**Screenshot of Work-in-progress**
capture d ecran 2016-04-19 a 16 19 39

Signed-off-by: Nick Papoutsis <admin@nils.gr>

### CODE REVIEW

**Comment by nikpap** [comment]
@jmartinm Checking out https://github.com/inspirehep/inspire-next/blob/invenio3/inspirehep/modules/records/jsonschemas/records/jobs.json, a lot of the fields are still WIP (`FIXME`). It might be based if they are finalized before or in conjunction with this PR. Relevant issue:  https://github.com/inspirehep/inspire-next/issues/265

**Comment by jmartinm** [comment]
@tomaszgy is removing a WIP here - https://github.com/inspirehep/inspire-next/pull/1041/files#diff-daa5913ef53c02da1885dd35ca6f9c49

Then there will be only 2 `FIXME` fields which should not be a big deal to block the development of the detailed page.

@tomaszgy are you going to tackle those? Or @kaplun you can check with @inspirehep/inspire-dir about those fields?

**Comment by jmartinm** [comment]
@nikpap when you have it partially ready, can you add a screenshot of the status? thanks.

**Comment by hoc3426** [comment]
The difference between HEPNames and HEPJobs for rank is that HEPNames has PHD, MAS and UG while HEPJobs bundles them all together as "Student".

**Comment by kaplun** [comment]
@hoc3426, indeed @tomaszgy was about to open RFC with precisely that question, in order to discuss openly whether to improve/harmonize these 2 lists between HEPNames and HEPJobs. New issue coming soon...

**Comment by nikpap** [comment]
Moved to https://github.com/inspirehep/inspire-next/pull/1083 based on master branch.

**Pull request closed without merging**
