### PR TITLE
mappings: `Mrs.` title

### PR DESCRIPTION
**Pull request by Panos512**
* Adds the option `Mrs.` to possible author titles.
* Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601678/

Signed-off-by: Panos Paparrigopoulos <panos.paparrigopoulos@cern.ch>

### CODE REVIEW

**Comment by Panos512** [comment]
Btw if you check https://inspirehep.net/search?cc=HepNames&ln=en&p=100__c%3A**&of=text&ot=100__c&rg=10100 there is a possible title `III`, but I think this is an error (it resembles to the `numeration` field values).

**Comment by david-caro** [comment]
LGTM, though this collides/is replaced by #1468 right?

**Comment by Panos512** [comment]
Yeah this will be useless when #1468 is merged. I can either close it or we merged it and let it die after 😃

**Comment by kaplun** [comment]
Yeah, I think this is to be considered superseded by #1468

**Pull request closed without merging**
