### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by jalavik**
Adds Travis CI testing for the overlay.

There are not many tests yet, we need to remember to continuously add more.
@jmartinm @pedrogaudencio @kaplun

### CODE REVIEW

**Comment by jmartinm** [comment]
Thanks for adding this. Looks good.

PS. This Travis PR is failing the Travis build. Inception.

**Comment by jalavik** [comment]
@jmartinm Hehe indeed. So there was an issue with Python 2.6 and I fixed now the `demosite populate` command. Let's see how this runs now.

**Comment by jacquerie** [comment]
It appears that, when running Travis on commit 275bdfe, something bad happened to Launchpad: https://travis-ci.org/inspirehep/inspire-next/builds/50058522#L167. This resulted in Travis not installing `nodejs` and thus failing to find `npm`: https://travis-ci.org/inspirehep/inspire-next/builds/50058522#L1255.

By the way, Chris Lea's PPA has been somewhat deprecated: https://nodesource.com/blog/chris-lea-joins-forces-with-nodesource. The installation instructions now use this other method: https://github.com/joyent/node/wiki/installing-node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions.

**Comment by jalavik** [comment]
@jacquerie Thanks for investigating! I will try to update the installation procedure.

**Comment by jalavik** [comment]
@jacquerie Woho, that did it. Thanks!

**Pull request merged**
