### PR TITLE
holdingpen: hide actions if workflow complete

### PR DESCRIPTION
**Pull request by david-caro**
Signed-off-by: David Caro <david@dcaro.es>

### CODE REVIEW

**Comment by jmartinm** [comment]
By looking at the code, looks 👍

**Comment by david-caro** [comment]
I've just found that there's some cases where the workflow is finished but it's not marked as completed, I'm investigating though I don't really think that the issue should be fixed here though.

**Comment by jmartinm** [comment]
Ok, just give the green light here when you think its ready and we can merge this PR.

**Comment by david-caro** [comment]
Found and fixed the issue somewhere else in the invenio-workflows code, this can be mereged :)

**Pull request merged**
