### PR TITLE
tests: fix imports in workflows tests

### PR DESCRIPTION
**Pull request by jacquerie**
Closes #1769

### CODE REVIEW

**Comment by jacquerie** [comment]
As the branch name says, I was hoping to integrate #1769 with this, but it's not ready. Merging this, so that we have one less thing to worry about.

**Comment by david-caro** [comment]
I don't see any changes on the license, did you forget them?

**Comment by jacquerie** [comment]
> I don't see any changes on the license, did you forget them?

Ctrl+C Ctrl+V :dancer:

**Comment by david-caro** [comment]
👍

**Pull request merged**
