### PR TITLE
907 workflows: make HP hep mapping non-dynamic

### PR DESCRIPTION
**Pull request by szymonlopaciuk**
## Description
This disables the default behaviour of the dynamic mapping creation, which can cause conflicts when two records with conflicting types, e.g. in extra_data, are indexed. Instead, this will only enable indexing on fields specified explicitly and will ignore the rest.

Also fixed a small mistake in docs related to the remapping.

### Manual tests ran (after remapping, unless specified otherwise)

| Test | Outcome (local) | Outcome (QA)
|---|---|---|
|new core arxiv harvest | OK (appears in inspire)| :arrow_left::ok: |
|new publisher harvest | OK (appears in inspire)| :arrow_left::ok: |
|update from arxiv | OK (updated in inspire)| :arrow_left::ok: |
|update from DESY | OK (updated in inspire)| :arrow_left::ok: |
|workflow errors when matched against WF in ERROR | OK (workflow in ERROR)| :arrow_left::ok: |
|article submission form blocks if submission WF has it | OK (displays a banner to the user that record is being reviewed)| :arrow_left::ok: |
|article submission form doesn't block if harvest WF has it | OK (let's the form pass through and stops the matching workflow [sets `workflow-stopped-by:#`])| :arrow_left::ok: |
|article submission form blocks if record is in inspire | OK (displays a banner that record is in inspire)| :arrow_left::ok: |
|remapping and reindexing run in HP with records in various states (during harvest) doesn't break the harvest| OK (records appear in inspire)| not easily reproducible, but various records in HP have survived the reindexing |
|literature submission card shows literature submissions|OK (shows)| :arrow_left::ok: |
|arxiv harvests card shows arxiv harvests|OK (shows)| :arrow_left::ok: |
|arxiv updates card shows arxiv update|OK (shows)| :arrow_left::ok: |
|publisher harvests card shows publisher harvest|OK (shows)| :arrow_left::ok: |
|publisher updates card shows publisher update|OK (shows)| :arrow_left::ok: |
|if `journal_coverage=full` reject button opaque in holdingpen|OK (button opaque)| :arrow_left::ok: |

## Related Issue
https://its.cern.ch/jira/browse/INSPIR-907

## Checklist:

- [x] I have all the information that I need (if not, move to `RFC` and look for it).
- [x] I linked the related issue(s) in the corresponding commit logs.
- [x] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [x] My code follows the code style of this project.
- [x] I've added any new docs if API/utils methods were added.
- [x] I have updated the existing documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by szymonlopaciuk** [comment]
ci test please

**Comment by szymonlopaciuk** [comment]
ci test please

**Comment by michamos** [comment]
did you also test all cards and facets?

**Comment by michamos** [comment]
What I mean is that this is a big change, lots of things may rely on the implicit mappings, and we have no tests for it. That sounds like a perfect recipe to break stuff, so I would be very careful.

**Comment by david-caro** [comment]
Yep, we know, it's a potentially dangerous change yes. We have some tests though, for some of the things (workflows matching each other, updates, new workflows...) but I agree that they are not enough.

**Comment by szymonlopaciuk** [comment]
@michamos @david-caro You were right there is a problem with the cards, in fact, user submissions are placed incorrectly. It's weird as even if I remap with the previous mapping and submit again it happens. I'm going to nuke my docker and try again, but anyway we can't merge this.

**Comment by david-caro** [comment]
On my local hp cards seem to work ok, I created manual submissions, new author, updated author, new arxiv harvest, arxiv update. Checking desy ones (publisher).

**Comment by david-caro** [comment]
Tested with publisher too. There was something about fully harvested journals that might use also elasticsearch right? Can you check that one?

**Comment by szymonlopaciuk** [comment]
@david-caro I wiped my docker ran your checks, and indeed it's working (as per updated table). What do you mean by fully harvested journals using ES?

**Comment by szymonlopaciuk** [comment]
@david-caro I can confirm that the HP works peoperly with the fully harvested journal UI indication

**Comment by szymonlopaciuk** [comment]
ci test please

**Comment by david-caro** [comment]
That's ok actually, as those are all author records :)

**Comment by szymonlopaciuk** [comment]
@david-caro I went on the `/holdingpen-hep/_mapping/hep` of QA elasticsearch master node endpoint and it seems you are right, the 'false' there is a string, which seems wrong?

**Comment by david-caro** [comment]
Yep, same here...

**Comment by szymonlopaciuk** [comment]
This seems to explain it: https://www.elastic.co/guide/en/elasticsearch/reference/current/boolean.html The field also accepts "strict" so probably the underlying schema defines as string, nevertheless it's a valid boolean

**Comment by david-caro** [comment]
Nice, it's even a bit more messy in 2.4 https://www.elastic.co/guide/en/elasticsearch/reference/2.4/boolean.html

**Comment by david-caro** [comment]
btw. the reindex shrinked the space usage in half (from >8 to <4 GB), and it took:
14871.29 user 329.51system 5:01:14 elapsed 84% CPU (0 avgtext + 0 avgdata 3551548 maxresident)k

For those I have no base level though....

**Comment by david-caro** [comment]
Let's get this going on :}

**Comment by david-caro** [comment]
ci merge please

**Comment by david-caro** [comment]
ci merge please

**Comment by david-caro** [comment]
something strange is happening...

**Comment by david-caro** [comment]
Fetching the code from github is extra slow... (56.00 KiB/s ) and it times out :/

**Comment by david-caro** [comment]
ci merge please

**Comment by david-caro** [comment]
it got broken :octocat:

**Comment by david-caro** [comment]
ci test please

**Comment by david-caro** [comment]
ci merge please

**Pull request merged**
