### PR TITLE
Closes #1532 fix autocomplete authors documentation

### LINKED ISSUE #1532: Author new form issues
The author creation form can be found in: http://inspire-nightly.cern.ch/submit/author/create

Current issues:

* [x] Autocompletion for Institution not working. [See file](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/forms/static/js/forms/affiliations_typeahead.js)
* [x] Autocompletion for Experiment not working. [See file](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/forms/static/js/forms/experiments_typeahead.js)
* [x] Autocompletion for Advisors not working. [See file](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/forms/static/js/forms/authors_typeahead.js)

Correct behaviour can be seen in http://labs.inspirehep.net/author/new

### PR DESCRIPTION
**Pull request by rikirenz**
add selenium tests documentation

### CODE REVIEW

**Comment by rikirenz** [comment]
@jmartinm @kaplun @jacquerie

**Comment by jacquerie** [comment]
#1605 looks a bit more general... Did you fix something else in your commit?

**Comment by jacquerie** [comment]
BTW, instead of writing "1532" in the PR name you can add "Closes #1532" to the body, and when your PR is merged the corresponding issue is automatically closed. Were you using Jira before, by any chance?

**Comment by rikirenz** [comment]
@jacquerie 
- no I did not fixed anything else.
- I will change the title. thanks!

**Pull request closed without merging**
