### PR TITLE
theme: use count instead of hits total

### PR DESCRIPTION
**Pull request by jacquerie**
Doesn't yet do what the title says, but the first two commits refactor the somewhat messy Jinja2 filters and add a few missing tests. There will be a third commit implementing what @eamonnmag suggested.

(I would also like to move ES logic into the controller from the template, but this PR will not yet do that.)

### CODE REVIEW

**Comment by jacquerie** [comment]
Now does what the title says.

**Comment by jacquerie** [comment]
Ready for review.

**Comment by jacquerie** [comment]
I have the suspicion that the problem of bogus counts being shown is more the result of caching by Flask/Jinja2 rather than using the incorrect method of ES.

**Comment by eamonnmag** [comment]
You are right. After further testing on my end, similar behaviour can be found on hepdata.net if you try long enough.

**Comment by jmartinm** [comment]
That could be, doing a quick search seems to be quite common 'problem' http://stackoverflow.com/a/27891981/890185

I guess because our input to the filter is constant it gets cached:

```
{{ "HEP" | number_of_records }}
```

If instead it was:

```
{{ RANDOM() | number_of_records }}
```

It wouldn't (according to the link above).

**Comment by jacquerie** [comment]
That doesn't look so bad. We could cache the result of the `count` query for 30/60 minutes, so that we don't constantly query ES, but constantly call the `number_of_records` filter using the `RANDOM` trick above. WDYT?

**Comment by jmartinm** [comment]
Yes, that could work. If jinja2 caches the whole template (not only the filter) then with this we will lose that caching so landing pages will always be recompiled on every request.

I am not sure if that would have a visible impact.

**Comment by jacquerie** [comment]
Ah, I was assuming the caching invalidation was per-filter, not per-page.

**Comment by jacquerie** [comment]
This can probably be merged, since I'm working on another PR to evict ES queries from filters that builds on top of this.

**Comment by kaplun** [comment]
@jacquerie can you rebase it? So that then we merge it?

**Comment by jacquerie** [comment]
Just sent a rebase your way. :ship:

**Pull request merged**
