### PR TITLE
refextract: Include `journal_titles` normalization in journal-kb

### LINKED ISSUE #2612: Refextract should also use the journal_titles for normalization
## Expected Behavior

When presented with a reference containing the full journal title of the journal, refextract should normalize it to the short title. For this to happen [`create_journal_kb_file`](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/refextract/tasks.py#L46) should also look at `journal_titles` instead of only `title_variants`.

### PR DESCRIPTION
**Pull request by zzacharo**
Signed-off-by: Zacharias Zacharodimos <zacharias.zacharodimos@cern.ch>

## Related Issue

Closes #2612 

## Checklist:

- [ ] I have all the information that I need (if not, move to `RFC` and look for it).
- [ ] I linked the related issue(s) in the corresponding commit logs.
- [ ] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [ ] My code follows the code style of this project.
- [ ] I've added any new docs if API/utils methods were added.
- [ ] I have updated the existing documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jacquerie** [comment]
> Actually this is incomplete because the requirements were [...]

If only there was a way to encode requirements in such a way that they are automatically verified... : )

**Comment by zzacharo** [comment]
@michamos https://github.com/inspirehep/refextract/blob/master/refextract/references/tag.py#L133 here I think it does some normalization in the reference line reagrding punctuation and spaces. Is all caps needed for the matching? For short_titles I can add them in the kb creation.

**Comment by jacquerie** [comment]
> If only there was a way to encode requirements in such a way that they are automatically verified... : )

You can use this as a pattern: https://github.com/jacquerie/inspire-next/commit/a60d040115b5f9428385261b8fc52d86b4302c39

**Comment by jacquerie** [comment]
My poor heart couldn't stand those files at 0% coverage, so I merged a commit like the one above that incorporated @kaplun's comments on it.

**Comment by michamos** [comment]
@jacquerie this should be revived now that we have modified the schema.

**Pull request closed without merging**
