### PR TITLE
search: return arxiv categories & affiliations from ES for LiteratureSearch

### PR DESCRIPTION
**Pull request by Dinika**
User-Story: [INSPIR-1316](https://its.cern.ch/jira/browse/INSPIR-1316)

Signed-off-by: Dinika Saxena <dinika.saxena@cern.ch>

## Checklist:

- [x] I have all the information that I need (if not, move to `RFC` and look for it).
- [x] I linked the related issue(s) in the corresponding commit logs.
- [x] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [x] My code follows the code style of this project.
- [ ] I've added any new docs if API/utils methods were added.
- [ ] I have updated the existing documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Dinika** [comment]
ci test please

**Comment by Dinika** [comment]
ci test please

**Comment by Dinika** [comment]
ci test please

**Comment by drjova** [comment]
@Dinika ``authors.affiliation`` is already there, why it doesn't work?

**Comment by Dinika** [comment]
@drjova there was a typo there (it should've been a plural)

**Comment by drjova** [comment]
ci merge please

**Pull request merged**
