### PR TITLE
dojson: fix earliest date parsing

### PR DESCRIPTION
**Pull request by jalavik**
Had to make some fixes for `earliest_date` field. @jacenkow

### CODE REVIEW

**Comment by jmartinm** [comment]
Looks :+1: 

Were these changes needed due to the `dojson` updates just merged?

**Comment by jalavik** [comment]
It has been bugged from the start I think. I discovered it when doing a submission.

**Comment by jmartinm** [comment]
Ah ok, strange that it was not crashing while loading demo records then.

**Comment by jalavik** [comment]
No wait. I think it was fine, perhaps submission was not following the new structure actually. I will amend this commit a bit and check how submissions are treating these fields.

**Comment by kaplun** [comment]
BTW, `earliest_date` is one of those derived fields that are needed to be computed for elasticsearch but we could avoid to store in MySQL. So in principle dojson should not be responsible for allocating it. Just pointing this out in case you are going to do further amendments.

**Comment by jalavik** [comment]
@jmartinm Yeah actually the schema reports these as not being lists while the dojson processing puts all these fields in a list. So in fact the original code was doing the right thing.

**Comment by jacenkow** [comment]
Yeah!

**Comment by jalavik** [comment]
PR adjusted

**Pull request merged**
