### PR TITLE
holdingpen: fix holdingpen-hep mapping for facets

### PR DESCRIPTION
**Pull request by szymonlopaciuk**
## Description
**See: https://its.cern.ch/jira/browse/INSPIR-907**

This fixes:
- 'Filter by action' facet

## Related Issue
Some facets in holdingpen don't have explicit mapping.

## Checklist:

- [ ] I have all the information that I need (if not, move to `RFC` and look for it).
- [ ] I linked the related issue(s) in the corresponding commit logs.
- [ ] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [ ] My code follows the code style of this project.
- [ ] I've added any new docs if API/utils methods were added.
- [ ] I have updated the existing documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by michamos** [comment]
have you checked all facets, or only that one?

**Comment by szymonlopaciuk** [comment]
@michamos From the code side the other ones are already there. On the UI side filters for status, source, subject are all working, as for collections I don't really know how to get anything other that `HEP` to show.

**Comment by szymonlopaciuk** [comment]
There seems to be a problem with sorting by relevance prediction actually, so looking into it...

**Comment by michamos** [comment]
:+1: collection seems to be the workflow name

**Comment by szymonlopaciuk** [comment]
In regards to the sorting for relevance prediction, it just doesn't work at all (always displays previous sorting). Also doesn't work on labs. I checked the mapping and there is a field for it, so makes me think a problem could be somewhere else. Any tips @drjova ?

**Comment by david-caro** [comment]
> +1 collection seems to be the workflow name

yep, just checked :)

**Comment by david-caro** [comment]
> as for collections I don't really know how to get anything other that HEP to show.

You can just search without restrictions, you should see, at least, Author, HEP, MERGE and on qa edit_article (yay for consistenci xd)

**Comment by szymonlopaciuk** [comment]
I created a dummy 'author' workflow on local to check and that facet also works. However I don't know if it should also appear in the holdingpen 'New Authors' card, cause if so, I just found another bug :/

**Comment by david-caro** [comment]
If you created with the author form it should.

**Comment by david-caro** [comment]
(it expects the `is-update` to have `false` or `true`)

**Comment by szymonlopaciuk** [comment]
From the form it works. From the code it threw an exception on no email of the submitter end ended up in ERROR state in harvests.

**Comment by szymonlopaciuk** [comment]
...I'm discovering so many things wrong I'll just keep updating the JIRA ticket for now...

**Comment by david-caro** [comment]
That's not related to this one right? this one actually fixes one of those issues no? (and as such can go in)

**Comment by szymonlopaciuk** [comment]
@david-caro It can on its own, you're right

**Comment by david-caro** [comment]
ci merge please

**Pull request merged**
