### PR TITLE
base: requirements.txt update

### PR DESCRIPTION
**Pull request by jmartinm**
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>

### CODE REVIEW

**Comment by jmartinm** [comment]
This seems to be the way to go to specify given version. Travis build passes, the right version of package  gets installed and we avoid using dependency links which [(might) disappear](https://github.com/pypa/pip/issues/2023)

**Comment by jalavik** [comment]
Cool. So I see that they have a '+' in front. Shall we add it to the other similar lines?

**Comment by jmartinm** [comment]
Note that all packages when a new release is done have a commit like: https://github.com/inveniosoftware/invenio-records/commit/571617218fd0430c551100f1d171c0dde38dd812

so we can then specify the new version if we need it.

**Comment by jmartinm** [comment]
I think that's just how the diff looks like? https://github.com/jmartinm/inspire-next/blob/master-elasticsearch-with-requirements/requirements.txt

There are no '+' in front.

**Comment by jalavik** [comment]
Haha yeah, sorry my bad.

**Comment by jmartinm** [comment]
Merged https://github.com/inspirehep/inspire-next/commit/104ee45df14578f16b03094ce825c59cda6a9f51

**Pull request closed without merging**
