### PR TITLE
WIP: formats: fixes errors caused by new model

### PR DESCRIPTION
**Pull request by ioannistsanaktsidis**
Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

### CODE REVIEW

**Comment by ioannistsanaktsidis** [comment]
@jmartinm I created this PR so as to fix all the errors occurred after the new model. I checked the bibtex for the demo records we have currently on Inspire and fixed the issues. I just need to check it for more records (e.g 8000) and then we can merge it.

**Comment by jmartinm** [comment]
@ioannistsanaktsidis great!

**Comment by jmartinm** [comment]
At the same time that you introduce the fixes for the new data model, tests need to be written for all the export formats so that future data model updates break the tests and we realize early on.

At the moment the coverage of the formats is very low:

```
inspire/utils/bibtex.py                                                               491    452     8%
inspire/utils/bibtex_booktitle.py                                                      43     43     0%
inspire/utils/cv_latex.py                                                             249    231     7%
inspire/utils/cv_latex_html_text.py                                                   136    123    10%
inspire/utils/export.py                                                                75     64    15%
inspire/utils/latex.py                                                                204    189     7%
```

Ideally the tests should cover 100% of those files. That will help get closer to the 100% dream coverage in the overlay.

**Comment by jmartinm** [comment]
This PR addresses https://github.com/inspirehep/inspire-next/issues/403

You can add it to the commit log message for nicer Github integration.

```
bibtex: fixes errors caused by new model

* (addresses #403)
```

**Comment by ioannistsanaktsidis** [comment]
After some changes that I made and also adding some tests the coverage for now is:
```
inspire/utils/bibtex.py                                                               501    327    35%
inspire/utils/bibtex_booktitle.py                                                      43     43     0%
inspire/utils/cv_latex.py                                                             249    231     7%
inspire/utils/cv_latex_html_text.py                                                   139     76    45%
inspire/utils/export.py                                                                75     21    72%
inspire/utils/latex.py                                                                210    124    41%
```

I didn't create test for bibtex_booktitle and cv_latex. The others are not complete yet, but there is a small improvement :P

**Comment by jmartinm** [comment]
Cool, going up steadily :)

**Pull request closed without merging**
