### PR TITLE
testsuite: new ViewsTests

### PR DESCRIPTION
**Pull request by kaplun**
* Introduces new testsuite for testing views.

* Adds new tests to access all existing records while checking none
  returns an error.

Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
cc @jmartinm

**Comment by jmartinm** [comment]
Very nice! So we have 3 broken records at the moment.

```
 [1110515, 1115448, 1210630]
```

@nikpap Can you look into it?

**Comment by kaplun** [comment]
Let me first double check because I have a set of fixes (based on new demo records) that might already solve this issue.

I'll add them as commit on top.

**Comment by kaplun** [comment]
Done. Let's see if there are still failing records. In that case I have no further fixes :smile:

**Comment by nikpap** [comment]
Hey @jmartinm , @kaplun the issue with the 2 later records might be that no collections are assigned to them.

When not logged in, this message appears:

```The record you are trying to access has just been submitted to the system and needs to be assigned to the proper collections. It is currently restricted for security reasons until the assignment will be fully completed. Please come back later to properly access this record.```

When logged in, the pages are rendered correctly but appear empty.

The first record seems to have another issue that will require further investigating ;)

PS. Let me know of the outcome

**Comment by kaplun** [comment]
Ha! Interesting that there are records without collections. My fix actually is for the Experiment dojson, related to dates, so these 3 records will likely still fail.

**Comment by kaplun** [comment]
OK Indeed Travis confirms the same errors. So you can go ahead with the investigation :+1:

**Comment by jmartinm** [comment]
Merged https://github.com/inspirehep/inspire-next/pull/505

**Pull request closed without merging**
