### PR TITLE
audit: dumping fix

### PR DESCRIPTION
**Pull request by Panos512**
- Reduces, a lot, the number of files that the dump creates by skiping
  non-valid audit records.

Signed-off-by: Panos Paparrigopoulos panos.paparrigopoulos@cern.ch

### CODE REVIEW

**Comment by jmartinm** [comment]
@david-caro is this the last version that worked ok for dumping in QA? If so, I can merge into `production`.

**Comment by david-caro** [comment]
@jmartinm  Yep, this one is ok as is

**Comment by jmartinm** [comment]
hmm, ok. I see in `production` branch there was a similar commit with different content https://github.com/inspirehep/inspire-next/commit/eb0ea189462d84f1840904370615ff5bbbe02748.

I will take this one and apply to `production` (hopefully merging correctly)

**Comment by jmartinm** [comment]
Merged https://github.com/inspirehep/inspire-next/commit/c14731ca84046478a586911fdcec7925a9127584

**Pull request closed without merging**
