### PR TITLE
format: HEP detailed record keywords

### PR DESCRIPTION
**Pull request by nikpap**
- [x] Adds free keywords to the HEP detailed record.
- [x] Styles keywords as labels.
- [x] Differentiates between INSPIRE and author-supplied keywords.
- [x] Fixes alignment.
- [x] Reduces keywords shown to 10.

Signed-off-by: Nick Papoutsis <admin@nils.gr>

### CODE REVIEW

**Comment by nikpap** [comment]
Here's how free keywords could look in the HEP detailed record. @jmartinm @annetteholtkamp are all "free_keywords" author supplied or are there any other categories as well?

capture d ecran 2015-11-26 a 15 43 38

**Comment by annetteholtkamp** [comment]
I find that less readable than the current display. It’s harder to see which keywords form a pair. 

- Annette

**Comment by jmartinm** [comment]
> I find that less readable than the current display. It’s harder to see which keywords form a pair.

I agree it is not very easy to distinguish them. We could use something like `chips` - http://materializecss.com/chips.html to separate them clearly.

By the way @annetteholtkamp , what about the questions asked by Nick regarding the headings of each of the keywords?

**Comment by annetteholtkamp** [comment]
On 30 Nov 2015, at 10:56, Javier Martin Montull <notifications@github.com> wrote:

> I find that less readable than the current display. It’s harder to see which keywords form a pair.
> 
> I agree it is not very easy to distinguish them. We could use something like chips - http://materializecss.com/chips.html to separate them clearly.
> 
> 
Yes, that could be nice.
> By the way @annetteholtkamp , what about the questions asked by Nick regarding the headings of each of the keywords?
> 
> 
Still on my list to ask DESY at standup today. 

- Annette

**Comment by nikpap** [comment]
@annetteholtkamp have there been any updates on this?

**Comment by annetteholtkamp** [comment]
I mentioned to Javier already that we’ll stay with just Inspire and author keywords - no further categories for the time being.

- Annette

**Comment by nikpap** [comment]
An updated version of it looks like, with keywords styled as labels:

capture d ecran 2015-12-02 a 15 10 56

**Comment by jmartinm** [comment]
@nikpap I guess the keywords are clickable?

And what about making them less dark? Something more like the one I mentioned the other day http://materializecss.com/chips.html

**Comment by nikpap** [comment]
Changed color to match the chips you've mentioned.

I think we also need to either reduce their number to <10 or increase the abstract length, because there's currently lots of white space under the abstract.

capture d ecran 2015-12-02 a 16 22 16

**Comment by jmartinm** [comment]
Indeed, the alignment seems off. The titles `Abstract` and `Keywords` should be at the same height and both the abstract text and the keywords should start at the same height.

And as you mention, would be good to make both the same total height. As we are in the detailed record I would show more of the abstract.

**Comment by nikpap** [comment]
Updated: 
capture d ecran 2015-12-03 a 16 31 27

**Comment by jmartinm** [comment]
Merged 9c28183898ac8d7e8fdcb04b8a5ee7c7eba75021

**Pull request closed without merging**
