### PR TITLE
dojson: changes url to urls

### PR DESCRIPTION
**Pull request by ioannistsanaktsidis**
* (addresses #434)

Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

### CODE REVIEW

**Comment by ioannistsanaktsidis** [comment]
@jmartinm  this PR is for the url problem in #434 that you mentioned.

**Comment by jmartinm** [comment]
We have to amend this test too https://github.com/inspirehep/inspire-next/blob/2294c1f848d2cd102cdfcb505f739c42944899a6/inspire/modules/deposit/testsuite/test_hep_submission.py#L195 and the code here https://github.com/inspirehep/inspire-next/blob/master/inspire/modules/deposit/dojson/fields/literature.py#L304

**Comment by ioannistsanaktsidis** [comment]
The first one I tried to change it and run the tests locally and it was
failing. Thats why I left it like this. We can check it tomorrow and see.

2015-10-26 17:18 GMT+01:00 Javier Martin Montull <notifications@github.com>:

**Comment by jmartinm** [comment]
Ok, they should be amended because otherwise all the submissions from users would not contains the URLs. Try it and if it does not work I can help out.

**Comment by ioannistsanaktsidis** [comment]
I am changing to urls the test_hep_submission.py, running the test and it
is failing saying  KeyError: 'urls'. My change is
this self.record['urls'][0]['url']. I also recreated the database so as to
apply my changes in the dojson. Ideas?

2015-10-27 8:37 GMT+01:00 Javier Martin Montull <notifications@github.com>:

**Comment by jmartinm** [comment]
You will have to update https://github.com/inspirehep/inspire-next/blob/master/inspire/modules/deposit/dojson/fields/literature.py#L298 and https://github.com/inspirehep/inspire-next/blob/master/inspire/modules/deposit/dojson/fields/literature.py#L310 so that the key is now `urls` instead of `url`

**Comment by ioannistsanaktsidis** [comment]
I have just amended the commit. The tests are good now in my local.

2015-10-27 10:45 GMT+01:00 Javier Martin Montull <notifications@github.com>:

**Pull request closed without merging**
