### PR TITLE
tasks: handle new record not yet in DB when indexing citations

### PR DESCRIPTION
**Pull request by ammirate**
Signed-off-by: Antonio Cesarano <cesarano2607@gmail.com>

### CODE REVIEW

**Comment by drjova** [comment]
there are other places which we have to change ``inspirehep.modules.records.exceptions`` to ``inspirehep.modules.records.errors``

**Comment by drjova** [comment]
ci merge please

**Comment by drjova** [comment]
ci merge please

**Comment by ammirate** [comment]
ci merge please

**Comment by ammirate** [comment]
ci merge please

**Comment by ammirate** [comment]
Ci merge please

**Pull request merged**
