### PR TITLE
global: remove invenio-collections dependency

### PR DESCRIPTION
**Pull request by szymonlopaciuk**
Signed-off-by: Szymon Łopaciuk <szymon@lopaciuk.eu>

## Checklist:

- [ ] I have all the information that I need (if not, move to `RFC` and look for it).
- [ ] I linked the related issue(s) in the corresponding commit logs.
- [ ] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [ ] My code follows the code style of this project.
- [ ] I've added any new docs if API/utils methods were added.
- [ ] I have updated the existing documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by szymonlopaciuk** [comment]
ci test please

**Comment by michamos** [comment]
Will this kind of searches still work? https://labs.inspirehep.net/search?page=1&size=25&cc=HAL%20Hidden

**Comment by michamos** [comment]
We seem to have (non-functioning) templates for it also: https://sentry.inspirehep.net/inspire-sentry/prod/issues/210464/

**Comment by szymonlopaciuk** [comment]
ci test please

**Comment by szymonlopaciuk** [comment]
@michamos I tired out the `/search?cc=HAL%20Hidden` type search, and they seem to be working. I assume it's because we store the collections as part of the record itself.

**Comment by szymonlopaciuk** [comment]
As for the [sentry error](https://sentry.inspirehep.net/inspire-sentry/prod/issues/210464/) the problem is that the page that request was trying to access, `/collections/`, is handled by invenio-collections, and their template param `collection` (https://github.com/inveniosoftware/invenio-collections/blob/master/invenio_collections/views.py#L63) collides with out param template. Some templates in inspire (e.g. https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/theme/templates/inspirehep_theme/header.html#L29) use the collection param (of type string) to render the correctly 'themed' page. However when rendering `/collections/` this parameter is instead provided by `invenio-collections` (and is of type of type Collection). This type mismatch is what triggers the exception. This page, however, would be removed when we remove `invenio-collections` falling back to the good old 404.

**Comment by szymonlopaciuk** [comment]
Regarding the permissions, the restricted collections are stored in the DB as collection names using `invenio-access`, and the actual query is built in inspire, against the record metadata itself, here: https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/search/api.py#L114. So it seems, as if `invenio-collections` are not used for enforcing permissions either.

**Comment by david-caro** [comment]
ci merge please

**Pull request merged**
