### PR TITLE
bibtex: implements bibtex

### PR DESCRIPTION
**Pull request by ioannistsanaktsidis**
* Adds Ajax handler for bibtex.

* Fixes errors in dojson fields.

* Fixes indentation to template file.

Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

### CODE REVIEW

**Comment by ioannistsanaktsidis** [comment]
@jmartinm  I am checking the Inspire_Default_HTML_brief.tpl now and I figured out that there are some bugs(e.g abstract) that are caused due to the change of the model. I guess in the demo sites that Nik is working should be fixed concerning that he uses the latest model. I can have a look tomorrow morning and I will inform accordingly! Cheers!

**Comment by jmartinm** [comment]
If you come up with some more fixes for `Inspire_Default_HTML_brief.tpl`, please create a different PR with them and I can merge it.

**Comment by jmartinm** [comment]
Using branch `master-rc` and `labs-rc` with the demo records I am getting the following error:

https://gist.github.com/anonymous/86614c3d6f55f2b54361

When accessing a search like:

`http://localhost:5000/search?cc=HEP`

With the default demo records of INSPIRE.

**Comment by ioannistsanaktsidis** [comment]
@jmartinm I amended the commit so now it is the latest version.

**Comment by jmartinm** [comment]
I am still getting the same error pointing to https://github.com/inspirehep/inspire-next/pull/307/files#diff-beee1e072567b244248ee4ec30407574R39

These are the records that are being rendered.

https://gist.githubusercontent.com/jmartinm/471fd792cf84eacd2ae9/raw/362578064319a9117ad5a50f946a5a3a6d925a65/records.json

**Comment by ioannistsanaktsidis** [comment]
Are you trying it with  master-rc and labs-rc ?

2015-08-21 14:50 GMT+02:00 Javier Martin Montull <notifications@github.com>:

**Comment by jmartinm** [comment]
Merged in `master-rc` which will become `master` soon.

**Pull request closed without merging**
