### PR TITLE
global: remove upgrade scripts

### PR DESCRIPTION
**Pull request by jacquerie**
As discussed IRL, past upgrade scripts are not run during the build, so they can be safely removed.

Skipping CI to avoid clogging the queue for more useful stuff. As soon as this is merged, coverage is expected to go up by ~5%.

### CODE REVIEW

**Comment by jalavik** [comment]
@jacquerie My bad for not being fully clear earlier, but unfortunately we cannot remove many of these **yet**. As I realize that most still needs to be run on production labs :/. I will give you a list of those we can remove.

**Comment by jacquerie** [comment]
Oh! I see. This is not high prority anyway, since it's just a coverage quick win, so for me this can be closed and the discussion postponed to when we run those scripts.

**Comment by jalavik** [comment]
You can safely remove:
```
inspirehep/modules/workflows/upgrades/inspire_2014_11_13_update_actions.py
inspirehep/modules/workflows/upgrades/inspire_2015_08_13_update_record_instances.py
inspirehep/modules/workflows/upgrades/workflows_2015_05_19_innodb_engine_and_keys.py 
```
On the other hand, we can also think about if it is better to just exclude upgrades from coverage reports instead of deleting them.

**Comment by jacquerie** [comment]
Arguments for removing: code that is not run should be deleted, since deleted code can be recovered from git history if needed. Arguments for keeping but excluding from coverage: documentation, and to save time if code must be retrieved frequently from git history.

I'm leaning towards deletion, maybe @kaplun and @jmartinm want to weigh in?

**Comment by kaplun** [comment]
I am ok with deleting because anyway, when we will move to Invenio 3, we are also very likely go for PostgreSQL. At that time no update will save us.

**Comment by jalavik** [comment]
@jacquerie @kaplun Fair points. I am okay with deleting.

**Comment by jmartinm** [comment]
Ok for me.

**Comment by jacquerie** [comment]
Not really relevant anymore.

**Pull request closed without merging**
