### PR TITLE
search: hep-authors improvements and search tests

### PR DESCRIPTION
**Pull request by chris-asl**
## Description
[WIP]
This is an effort to automate the author search test and avoid having
regressions when changing inspire-query-parser functionality.

The idea is to have a dataset for each search category we're trying to
improve searching on. That's the reason for having a separate
`search_api_client` fixture, which spins up an application with the
`FIXTURES_FILE` that was defined in each search test module.

### Notes

- Although, this PR uses the two name variations, in the current (unreleased version of `inspire-query-parser`), only one name variations field is being used and the tests are passing. 
 That means that we might be able to avoid having two name variations.
- These tests are not to be run in our usual test suite, but mainly by whom is doing changes in the parser each time.

## Checklist:

- [ ] I have all the information that I need (if not, move to `RFC` and look for it).
- [ ] I linked the related issue(s) in the corresponding commit logs.
- [ ] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [ ] My code follows the code style of this project.
- [ ] I've added any new docs if API/utils methods were added.
- [ ] I have updated the existing documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bavaria95** [comment]
run tests

**Comment by bavaria95** [comment]
run tests

**Comment by bavaria95** [comment]
run tests

**Comment by chris-asl** [comment]
run tests

**Comment by bavaria95** [comment]
run tests

**Comment by bavaria95** [comment]
run tests

**Comment by chris-asl** [comment]
Last commit is targeted towards https://github.com/inspirehep/inspire-next/issues/3055 and specifically:

- `a stein,e` and `a stein,E`
- `a oz, y` and `a oz, y.`

**Comment by jacquerie** [comment]
Is this PR missing commits? I only see one that modifies the tests, but I see no mapping changes.

**Comment by chris-asl** [comment]
No, they're not missing.

Initially I had some changes to the name variations after receiving them from `inspire-utils`, which were pulled upstream, like lowercasing. 

Additionally, we had added another field in the full_name with another analyzer. After some changes, the extra field was more or less the same with the `full_name`. 

So, I removed it, run my tests from here, all of them passed.
In addition to that, did some tests with Stella in my nightly with that analyzer removed (simply querying only the `full_name` field) and they also worked fine. 

That's why this PR doesn't require now any changes.

**Comment by jacquerie** [comment]
> No, they're not missing.

Ok, then I can close this because all these changes are already in https://github.com/inspirehep/inspire-next/pull/3128.

**Pull request closed without merging**
