### PR TITLE
dojson: support enhanced marcxml links

### LINKED ISSUE #485: dojson: support for enhanced MARCXML links
https://github.com/inspirehep/inspire/commit/de148e839653c18ad0c6572874ffe85702509482 and followed up commits have introduced several links across records.
```    
         100/700 $x with Record ID of linked HepName,
                 $y with True/False if the signature is claimed
                 $z with Record ID of institution
         371/110 $z with Record ID of institution
         502     $z with Record ID of institution
         999C5   $0 with on the fly discovered Record IDs (not for books)
         773     $0 with Record ID of corresponding Book or Proceeding
                 $1 with Record ID of corresponding Journal
                 $2 with Record ID of corresponding Conference
         693/710 $0 with Record ID of corresponding experiment
```

Dojson scripts should amended accordingly to translate this links from MARCXML into JSON.
* [x] `100/700 $x` in HEP should go to `authors[].recid`
* [x] `100/700 $y` in HEP should go to `authors[].curated_relation` (in `dojson` this is currently called `claimed`)
* [x] `100/700 $z` in HEP should go to `authors[].affiliations[].recid` (`curated_relation` is set to `true` if there is a recid.
* [x] `502 $z` in HEP should go to `thesis[].recid` (`curated` blablabla)
* [x] `371 $z` in HepNames should go to `positions[].institution.recid` (`curated_relation to `true`)
* [x] `110 $z` in Jobs should go to `institution.recid` (`curated_relation to `true`)
* [x] `999C5  $0` in HEP should go into `references[].recid`
* [x] `773 $0` in HEP should go into into new `book.recid` field if `BOOKCHAPTER`
* [x] `773 $1` in HEP should go into `publication_info.journal_recid` (which should be added to `hep-0.0.1.json`
* [x] `773 $2` in HEP should go into `publication_info.recid`
* [x] `693 $0`in HEP should go to `accelerator_experiment.recid` (`curated_relation` set to `true`)
* [x] `710 $0`in HEP should go to `collaboration.recid` (does not exist yet.)

### PR DESCRIPTION
**Pull request by ioannistsanaktsidis**
* 100/700 $x with Record ID of linked HepName,
          $y with True/False if the signature is claimed
          $z with Record ID of institution

* 371/110 $z with Record ID of institution

* 502 $z with Record ID of institution

* 999C5 $0 with on the fly discovered Record IDs (not for books)

* 773 $0 with Record ID of corresponding Book or Proceeding
	  $1 with Record ID of corresponding Journal
	  $2 with Record ID of corresponding Conference

* 693/710 $0 with Record ID of corresponding experiment

* Closes #485.

Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>
Co-authored-by: Javier Martin Montull <javier.martin.montull@cern.ch>

### CODE REVIEW

**Comment by annetteholtkamp** [comment]
701__z for record ID of institution of supervisor

773 $0 with Record ID of corresponding Book or Proceeding or Report

- Annette


On Jan 13, 2016, at 10:40 AM, ioannistsanaktsidis <notifications@github.com<mailto:notifications@github.com>> wrote:


  *   100/700 $x with Record ID of linked HepName,
$y with True/False if the signature is claimed
$z with Record ID of institution

  *   371/110 $z with Record ID of institution

  *   502 $z with Record ID of institution

  *   999C5 $0 with on the fly discovered Record IDs (not for books)

  *   773 $0 with Record ID of corresponding Book or Proceeding
$1 with Record ID of corresponding Journal
$2 with Record ID of corresponding Conference

  *   693/710 $0 with Record ID of corresponding experiment

  *   Closes #485<https://github.com/inspirehep/inspire-next/issues/485>.

Signed-off-by: Ioannis Tsanaktsidis ioannis.tsanaktsidis@cern.ch<mailto:ioannis.tsanaktsidis@cern.ch>
Co-authored-by: Javier Martin Montull javier.martin.montull@cern.ch<mailto:javier.martin.montull@cern.ch>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/inspirehep/inspire-next/pull/706

Commit Summary

  *   dojson: support enhanced marcxml links

File Changes

  *   M inspirehep/base/searchext/mappings/hep.json<https://github.com/inspirehep/inspire-next/pull/706/files#diff-0> (3)
  *   M inspirehep/base/templates/format/record/Inspire_Default_HTML_general_macros.tpl<https://github.com/inspirehep/inspire-next/pull/706/files#diff-1> (6)
  *   M inspirehep/dojson/hep/fields/bd1xx.py<https://github.com/inspirehep/inspire-next/pull/706/files#diff-2> (15)
  *   M inspirehep/dojson/hep/fields/bd5xx.py<https://github.com/inspirehep/inspire-next/pull/706/files#diff-3> (7)
  *   M inspirehep/dojson/hep/fields/bd6xx.py<https://github.com/inspirehep/inspire-next/pull/706/files#diff-4> (11)
  *   M inspirehep/dojson/hep/fields/bd70x75x.py<https://github.com/inspirehep/inspire-next/pull/706/files#diff-5> (11)
  *   M inspirehep/dojson/hep/fields/bd76x78x.py<https://github.com/inspirehep/inspire-next/pull/706/files#diff-6> (12)
  *   M inspirehep/dojson/hep/model.py<https://github.com/inspirehep/inspire-next/pull/706/files#diff-7> (15)
  *   M inspirehep/dojson/hep/schemas/hep-0.0.1.json<https://github.com/inspirehep/inspire-next/pull/706/files#diff-8> (4)
  *   M inspirehep/dojson/hepnames/fields/bd1xx.py<https://github.com/inspirehep/inspire-next/pull/706/files#diff-9> (9)
  *   M inspirehep/dojson/jobs/fields/bd1xx.py<https://github.com/inspirehep/inspire-next/pull/706/files#diff-10> (7)
  *   M inspirehep/utils/bibtex.py<https://github.com/inspirehep/inspire-next/pull/706/files#diff-11> (4)
  *   M inspirehep/utils/cv_latex.py<https://github.com/inspirehep/inspire-next/pull/706/files#diff-12> (2)
  *   M inspirehep/utils/cv_latex_html_text.py<https://github.com/inspirehep/inspire-next/pull/706/files#diff-13> (3)
  *   M inspirehep/utils/latex.py<https://github.com/inspirehep/inspire-next/pull/706/files#diff-14> (2)
  *   A tests/fixtures/test_hep_book.xml<https://github.com/inspirehep/inspire-next/pull/706/files#diff-15> (783)
  *   M tests/fixtures/test_hep_record.xml<https://github.com/inspirehep/inspire-next/pull/706/files#diff-16> (2)
  *   M tests/test_hep.py<https://github.com/inspirehep/inspire-next/pull/706/files#diff-17> (18)

Patch Links:

  *   https://github.com/inspirehep/inspire-next/pull/706.patch
  *   https://github.com/inspirehep/inspire-next/pull/706.diff

**Comment by jmartinm** [comment]
Event though the current tests pass, they are not strict enough. In my local machine after loading the demo records I get 253 records (while 426 should be present)

I created this test https://github.com/inspirehep/inspire-next/pull/719. Will merge it once it is green on Travis. You can already take it and test locally.

**Comment by jmartinm** [comment]
Can you rebase with master now that https://github.com/inspirehep/inspire-next/pull/719 is merged?

**Comment by ioannistsanaktsidis** [comment]
Yes I will rebase and push. The problem is that I also detect the same problem with the indexing, which was not happening yesterday :/ I will check again and push. Cheers.

**Pull request merged**
