### PR TITLE
templates: adds missing parts in brief and detailed

### LINKED ISSUE #542: Literature detailed: Author display improvements
Based on the current implementation for inspirehep, author display has to be amended:

https://github.com/inspirehep/inspire/blob/master/bibformat/format_elements/bfe_INSPIRE_authors.py#L27

Important to note the logic about displaying corporate authors and collaborations.

### LINKED ISSUE #597: Brief and detailed production check
Brief and detailed formats still lack some basic information that is currently displayed on production.

This is more obvious in some of the records:

screen shot 2015-12-01 at 5 20 17 pm

The current [brief](https://github.com/inspirehep/inspire/blob/master/bibformat/format_templates/Default_HTML_brief.bft) and [detailed](https://github.com/inspirehep/inspire/blob/master/bibformat/format_templates/Default_HTML_detailed.bft) formats need to be reviewed, and the missing information needs to be added (prior decision if the information is still relevant)

Also the following needs to be fixed:

* [ ] Avoid blind capitalization - titles are being capitalized which does not make sense in most cases (due to acronyms or other parts of the title meant to be in capital letters). Only if a title is all in capital letters (like some older records) we should capitalize the title.

In order to compare one can search any record in inspirehep.net to see how it is currently displayed.

@ioannistsanaktsidis can you have a look?

### PR DESCRIPTION
**Pull request by ioannistsanaktsidis**
* Closes #597.

* Closes #542.

* Addresses #328.

Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

### CODE REVIEW

**Comment by ioannistsanaktsidis** [comment]
@jmartinm  till now I have only seen that the publication info is not displayed correctly. I fixed that problem and also the capitalization problem of the titles. I will take one more look but I think evth else is ok. I will inform you so as to check the PR and merge it. Cheers.

**Comment by jmartinm** [comment]
There were also report numbers missing, can you identify that code in the legacy format?

And can you sync with @nikpap , as the eprint category is added in one of his PRs - https://github.com/inspirehep/inspire-next/pull/562

**Comment by jmartinm** [comment]
And this commit https://github.com/inspirehep/inspire-next/commit/f1c47dcc0ed1e60337387f53212859d7252e277d added Collaboration display but there are some other fields involved in the legacy format (like corporate author field) that might be missing

**Comment by ioannistsanaktsidis** [comment]
Also about the year field which is this one
https://github.com/inspirehep/inspire/blob/master/bibformat/format_elements/bfe_INSPIRE_date.py
I should apply the whole functionality for our case right?

2015-12-02 15:57 GMT+01:00 Javier Martin Montull <notifications@github.com>:

**Comment by jmartinm** [comment]
It might not be needed. We have the same logic in the calculation of the `earliest_date` field so we can use that field.

**Comment by ioannistsanaktsidis** [comment]
Perfect then !
Στις 2 Δεκ 2015 6:14 μ.μ., ο χρήστης "Javier Martin Montull" <
notifications@github.com> έγραψε:

**Comment by ioannistsanaktsidis** [comment]
@jmartinm when you have time we can start check this PR. I think all the missing parts are addressed.

**Comment by jmartinm** [comment]
superseded by https://github.com/inspirehep/inspire-next/pull/655

**Pull request closed without merging**
