### PR TITLE
search results: adds number and checkbox in front of every result

### PR DESCRIPTION
**Pull request by ioannistsanaktsidis**
Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

### CODE REVIEW

**Comment by jmartinm** [comment]
Can you make the checkbox and numbers show closer to the brief content?

screen shot 2015-09-01 at 2 55 26 pm

**Comment by ioannistsanaktsidis** [comment]
@jmartinm now I think is better.

**Comment by jmartinm** [comment]
Yes it does. Shall we wait until the Export button is working to merge this? At the moment there is nothing one can do with the checkboxes

**Comment by ioannistsanaktsidis** [comment]
Yes, sure!

2015-09-02 9:18 GMT+02:00 Javier Martin Montull <notifications@github.com>:

**Comment by jmartinm** [comment]
Closing this for the moment until we implement full functionality of checkboxes and Export.

**Pull request closed without merging**
