### PR TITLE
Workflows migration

### PR DESCRIPTION
**Pull request by jmartinm**
Superseeds https://github.com/inspirehep/inspire-next/pull/1226

### CODE REVIEW

**Comment by jmartinm** [comment]
Rebased and updated this PR. I have tested successfully to load into the DB the dump from labs.

The legacy HP entries do not go into ElasticSearch because their `data_type` does not match the configuration of types that go into ES:

```python
In [1]: app.config['WORKFLOWS_UI_DATA_TYPES']
Out[1]:
{'authors': {'search_index': 'holdingpen-authors', 'search_type': 'authors'},
 'hep': {'search_index': 'holdingpen-hep', 'search_type': 'hep'}}
```

This is a good thing though because sending them to ES causes errors due to the data model inside the workflow objects not being compatible with the [mappings](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/workflows/mappings/holdingpen/authors.json).

I think we can update the Holding Pen mappings so that they reflect the new data model and for older HP entries they will be in the database but will not appear in the HP search.

**Comment by jmartinm** [comment]
After checking with @jalavik we need to:

* [ ] Merge the commits related to the dump functionality that are in `production` branch into this PR.

* [ ] Remove current 500 record limit (https://github.com/inspirehep/inspire-next/commit/896241ab9674a7105386dba3a07af04f904a1c7b#diff-eb226742d3dff161b6730019a569a325R63). We need to be careful not to load too many rows into memory and run out of it.

**Comment by kaplun** [comment]
So this PR can in principle be merged?

**Comment by jmartinm** [comment]
Not yet, I am currently working on it to solve existing issues on the dumping and loading.

**Comment by jmartinm** [comment]
This is now ready as far as I can see.

**Pull request merged**
