### PR TITLE
dojson: more languages

### PR DESCRIPTION
**Pull request by kaplun**
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by jacquerie** [comment]
Let's take this bull by the horns.

From the following query: https://inspirehep.net/search?ln=en&ln=en&p=041__a%3A**+or+0410_a%3A**+or+0411_a%3A**&of=text&ot=041__a,0410_a,0411_a&rg=40000, using the following Bash one-liner:
```shell
$ cut -f 3 -d '$' 041.txt | cut -c 2- | sort | uniq -c | sort -n
```
we get:
```
   1 Belgian
   1 Chiefly Japanese, others English
   1 Chiefly in English, some in Japanese
   1 English / Japanese
   1 English or French
   1 English or Japanese
   1 English, French, and German
   1 English, German, Russian
   1 English, Russian, Kazakh
   1 English, french
   1 English/Japanese
   1 French, Romanian
   1 Galician
   1 German and French
   1 German mostly
   1 German translated from Russian
   1 Japanese/English
   1 Lithuanian
   1 Malay
   1 Most papers in English, some in Japanese
   1 Mostly French
   1 Mostly Japanese, some English
   1 Mostly Russian, some English
   1 Portuguese, Esperanto
   1 Russian or German
   1 Russian, English
   1 SPANISH
   1 Serbian
   1 Slovak
   1 Slovenian
   1 Slovenian, English
   1 ja
   1 mostly Japanese, some English
   2 Catalan
   2 Croatian
   2 Danish
   2 German and English
   2 Hebrew
   2 Italian and English
   2 Japanese or English
   2 Latin
   2 Mostly English, some Japanese
   2 Mostly Japanese
   2 Multiple
   2 Portuguese, English
   2 Russian / English
   2 Serbo-Croatian
   2 spanish
   3 English and Russian
   3 English or Russian
   3 English, French
   3 French or English
   3 Korean
   3 Spanish, English
   3 english
   4 English and Japanese
   4 Esperanto
   5 Bulgarian
   5 Czechoslovakian
   5 Finnish
   5 Persian
   6 English
   6 Hungarian
   6 Indonesian
   7 RUSSIAN
   7 Russian or English
   7 Turkish
   8 Czech
   8 Japanese and English
   9 FRENCH
   9 ITALIAN
   9 Norwegian
   9 Swedish
  10 French and English
  11 Russian and English
  14 german
  15 GERMAN
  15 Greek
  16 Romanian
  18 English and French
  19 Dutch
  21 Ukrainian
  30 french
  52 English, Russian
  61 Polish
 213 Chinese
 255 Portuguese
 257 Spanish
 350 Japanese
 774 Italian
4612 French
4996 German
19401 Russian
```

**Comment by kaplun** [comment]
I did it :wink: that's how I built my map:
https://app.asana.com/0/inbox/3720556472136/64806285149807/64711366147697

**Comment by jacquerie** [comment]
Ah, I arrived late to the party : )

Do you want to add more commits here, or are you going to submit other PRs?

**Comment by kaplun** [comment]
No I thing I am done for this one.

**Comment by kaplun** [comment]
P.s. my fault :) I should have linked the Asana ticket from the start.

**Pull request closed without merging**
