### PR TITLE
brief: fixes abstract problem

### PR DESCRIPTION
**Pull request by ioannistsanaktsidis**
Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

### CODE REVIEW

**Comment by jmartinm** [comment]
What was the problem exactly? Please, add a bit longer description in the commit

**Comment by jmartinm** [comment]
ping @ioannistsanaktsidis was this needed?

**Comment by ioannistsanaktsidis** [comment]
@jmartinm sorry for not replying, I just saw the messages. The problem was that sometimes the record had 2 abstracts e.g the arxiv one and another one. Till now both of them appeared. The commit ensures that when the arxiv one exists it will be the one displayed.
Cheers!

**Comment by jmartinm** [comment]
Merged f4cfe202aa0397877734e3a270a0bd215389602a

**Comment by annetteholtkamp** [comment]
Shouldn’t it be the other way around? Show publisher abstract with priority, arxiv as a clickable link?

- Annette

**Comment by jmartinm** [comment]
You are right @annetteholtkamp 

@ioannistsanaktsidis if there are 2 abstracts, in the brief results the one from the publisher should be the one shown (see the current logic here https://github.com/inspirehep/inspire/blob/master/bibformat/format_elements/bfe_INSPIRE_abstract.py#L75)

And then in the detailed view we can show the second abstract ( that you can leave for @nikpap )

**Pull request closed without merging**
