### PR TITLE
WIP schemas: ORCID with letters

### PR DESCRIPTION
**Pull request by Dziolas**
* Changes ORCID field pattern to support letters

Signed-off-by: Wojciech Ziółek <wojciech.ziolek@cern.ch>

### CODE REVIEW

**Comment by Dziolas** [comment]
@jmartinm Do you want me also to update dojson to remove "orcid:" from the beginning of string?

**Comment by jacquerie** [comment]
Uhm, http://support.orcid.org/knowledgebase/articles/116780-structure-of-the-orcid-identifier says that only the last character might be an X, while all others should be digits. Did they change from this? In any case, our current pattern is wrong.

BTW have a look at #1392 to see where identifiers are goings.

**Comment by jmartinm** [comment]
Do you have the example with the letters @Dziolas ?

No worries about DOJSON, we will clean it up after https://github.com/inspirehep/inspire-next/pull/1392 is merged.

**Comment by Dziolas** [comment]
Ah sorry, I didn't check that. I just saw the las character being X and I assumed that there might be more. I will change it.

**Comment by Dziolas** [comment]
Closing as Jacopo created new pull request already.

**Pull request closed without merging**
