### PR TITLE
utils: catch IndexError in get_value and return default

### PR DESCRIPTION
**Pull request by liamkirsh**
Signed-off-by: Liam Kirsh <liam.kirsh@cern.ch>

### CODE REVIEW

**Comment by jacquerie** [comment]
This needs a rebase, but it should be ok to go. Shall I come over to help?

**Comment by liamkirsh** [comment]
Thanks. Should be rebased on top of master now.

**Comment by jacquerie** [comment]
Whoops, sorry, I missed one thing: in the commit message `get_value` should be `utils`, since there we put the module of the function you are modifying.

**Comment by liamkirsh** [comment]
Comme ça?

**Pull request closed without merging**
