### PR TITLE
WIP Integrate Invenio-Matcher

### PR DESCRIPTION
**Pull request by jacquerie**
Currently there's some preliminary work to better test the current matching. Actual integration coming soon.

### CODE REVIEW

**Comment by kaplun** [comment]
What's the plan for this integration?

**Comment by jacquerie** [comment]
The idea is to integrate it in `inspire.modules.workflows.tasks.matching`. The proposal is to create alternative versions of each task using `invenio-matcher`, probably using the helper functions that this PR currently added tests for.

**Comment by jacquerie** [comment]
So, the first commit contains a few tests for `inspirehep/modules/workflows/tasks/matching.py`. In particular it contains a trick to test tasks in isolation which might prove useful in the future.

The second commit contains an example of integration of `Invenio-Matcher`. You probably don't want to use it as it is, since it's not unwrapping the `MatchResult` objects returned by `Invenio-Matcher`, but it's a trivial modification to make, and the API for `MatchResult` is still very much in flux.

**Comment by jalavik** [comment]
Continued in #678

**Pull request closed without merging**
