### PR TITLE
deposit: robotupload with priority

### PR DESCRIPTION
**Pull request by kaplun**
* Sends robotupload requests by setting corresponding priority to 5,
  so that literature suggestions and authors additions are treated
  promptly.

Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
@jalavik, @jmartinm I am adding this as requested by @annetteholtkamp to give robotupload requests high prirority like regular bibedit.

(I am not touching priority for harvesting-related robotuploads).

**Comment by jmartinm** [comment]
👍  Looks good, this change should end up in `production` branch for it to be deployed. I wonder what is the current status of `master` vs `production` branches.

**Comment by jalavik** [comment]
@jmartinm `master` could be made into `invenio3` now I think..

**Comment by kaplun** [comment]
Ouch. Should I recreate the PR against `production`?

**Comment by jmartinm** [comment]
Yes, I think both comments make sense :)

**Pull request closed without merging**
