### PR TITLE
search: topcite keyword

### PR DESCRIPTION
**Pull request by Panos512**
* Adds `topcite` and `cited` keyword support.

* Should be merged with inspirehep/invenio-query-parser#11 .

* Closes box no.9 of #817.

Signed-off-by: Panos Paparrigopoulos <panos.paparrigopoulos@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
Can you add a test to prove that topcite works as it should? (also amending the version.py) Thanks!

**Comment by jacquerie** [comment]
> Can you add a test to prove that topcite works as it should? (also amending the version.py) Thanks!

:+1:

Here's an integration test that does this:

```python
from invenio_testing import InvenioTestCase

import json


class SearchTests(InvenioTestCase):

    def _search(self, p):
        url = '/search?cc=hep&sf=earliest_date&of=id&p={p}'.format(p=p)
        data = self.client.get(url).data
        result = map(int, json.loads(data))

        return result

    def test_topcite(self):
        self.assertTrue(self._search('find topcite 3'))
```

**Comment by jacquerie** [comment]
In fact, the same idea could be used to recast all queries in #817 (and in general, all queries we want to keep track for regressions) as failing tests.

**Comment by kaplun** [comment]
@Panos512 I think this code hasn't been integrated into Invenio3. Can you open a new PR against Invenio3 branch, and then we close this one?

**Comment by Panos512** [comment]
@kaplun I think it's already merged ( https://github.com/inspirehep/inspire-next/pull/946 )

**Pull request closed without merging**
