### PR TITLE
dojson: fixes records with issues

### LINKED ISSUE #724: Records with dojson issues
The following record ids had problems with the dojson conversion and were not imported into QA.

```
mysql> select recid from inspire_prod_records where successful=0;
+---------+
| recid   |
+---------+
|  875992 |
|  902713 |
|  902929 |
|  903421 |
|  903628 |
|  903978 |
|  904059 |
|  904060 |
|  905285 |
|  905456 |
|  907094 |
|  907124 |
|  907494 |
|  907499 |
|  908037 |
|  908393 |
|  908545 |
|  908970 |
|  909194 |
|  910415 |
|  910912 |
|  911032 |
|  911171 |
|  911211 |
|  911217 |
|  911254 |
|  911371 |
|  911373 |
|  911378 |
|  911464 |
|  911475 |
|  911486 |
|  911565 |
|  912069 |
|  912159 |
|  912243 |
|  912256 |
|  912287 |
|  963646 |
|  963792 |
|  963914 |
|  963983 |
|  964119 |
|  966446 |
|  973675 |
|  978993 |
|  982820 |
|  984867 |
|  985409 |
|  992628 |
|  997806 |
| 1000017 |
| 1007375 |
| 1041387 |
| 1063771 |
| 1063883 |
| 1065894 |
| 1065930 |
| 1066385 |
| 1069252 |
| 1069341 |
| 1069610 |
| 1072398 |
| 1075461 |
| 1076348 |
| 1078880 |
| 1115606 |
| 1122033 |
| 1125505 |
| 1127460 |
| 1182113 |
| 1212635 |
| 1213074 |
| 1213104 |
| 1213500 |
| 1214390 |
| 1220831 |
| 1225384 |
| 1240986 |
| 1273732 |
| 1281890 |
| 1292531 |
| 1347160 |
| 1352751 |
| 1402654 |
+---------+
85 rows in set (0.00 sec)
```

The XML of those records can be downloaded here - https://www.dropbox.com/s/u0kzttahwsq5vle/wrong-marcxml.xml?dl=0

`dojson` needs to be amended.

### PR DESCRIPTION
**Pull request by ioannistsanaktsidis**
* Closes #724.

Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
Does that mean that all the broken records in #724 are now loadable after these fixes?

**Comment by kaplun** [comment]
Can you detail in the commit log what you have fixed?

**Comment by ioannistsanaktsidis** [comment]
After these fixes I think everything will be ok. I will make a test to
check them all. I will comment thoroughly about it tomorrow. Cheers :D

**Comment by ioannistsanaktsidis** [comment]
@kaplun yes after that fixes all the records that are in the #724 will be available for loading.

**Comment by ioannistsanaktsidis** [comment]
Just applied the latest changes. I want to check one last thing and then we can merge it.

**Comment by ioannistsanaktsidis** [comment]
@jmartinm  after making the latest changes there is a last error occuring in detailed views.
screen shot 2016-01-26 at 15 39 07
Any ideas? Looks like a problem from invenio_base?

**Comment by ioannistsanaktsidis** [comment]
Solved!

**Comment by ioannistsanaktsidis** [comment]
Just updated the latest changes. It is ready for checking and merging. Cheers.

**Comment by jmartinm** [comment]
@ioannistsanaktsidis Can you rebase this branch? We need to merge it to avoid the crashes on the production synchronization.

**Comment by ioannistsanaktsidis** [comment]
@jmartinm  yes I am taking care now, I will push in a 5.

**Comment by ioannistsanaktsidis** [comment]
@jmartinm  Updated!

**Comment by ioannistsanaktsidis** [comment]
@jmartinm this one is ready. We can test it and merge it.

**Pull request merged**
