### PR TITLE
migrator: fix record update during migration

### PR DESCRIPTION
**Pull request by jalavik**
Co-authored-by: Samuele Kaplun <samuele.kaplun@cern.ch>
Signed-off-by: Jan Aage Lavik <jan.age.lavik@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
Why Travis isn't running?

**Comment by kaplun** [comment]
BTW were you also preparing a test do demonstrate the update?

**Comment by jalavik** [comment]
@kaplun Had some trouble with the test, let's look together IRL.

**Comment by jalavik** [comment]
@kaplun Nevermind, got the test working :)

**Pull request merged**
