### PR TITLE
WIP jsonschema: no additionalProperties

### PR DESCRIPTION
**Pull request by kaplun**
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by jacquerie** [comment]
This was a very optimistic commit : )

We will resuscitate this commit and apply it on top after we:

1. Solve all Sentry issues
2. Make the DoJSON rules and the schemas coherent for all collections

**Comment by kaplun** [comment]
Ah sure :dancer: it's a WIP. But it's a tool to address your second point. 2. is not valid if this commit is included.

**Comment by jacquerie** [comment]
> But it's a tool to address your second point. 2. is not valid if this commit is not included and passing.

Yup, that's the trick to do it: you add this commit, you WIP on top until you pass the validation, then you squash your WIPs and put this commit last : )

**Comment by kaplun** [comment]
Exactly that's what I had in mind

**Comment by jacquerie** [comment]
Moved to https://github.com/inspirehep/inspire-schemas/issues/26.

**Pull request closed without merging**
