### PR TITLE
WIP Es improvements

### PR DESCRIPTION
**Pull request by kaplun**
I am trying here to clean up hep.json in order to make explicit all tokenizers and many more features... this is completely WIP

### CODE REVIEW

**Comment by jmartinm** [comment]
For all the fields that we define as `not_analyzed`, shall we instead have a custom one that lowercases?

**Comment by kaplun** [comment]
Yep. Although not e.g. URLs and DOIs which are case sensitive.

**Comment by jmartinm** [comment]
> Yep. Although not e.g. URLs and DOIs which are case sensitive.

Even though technically speaking that might the case, at least I would hope that a url matches even if I write it in upper case. Isn't it the case noways in production?

**Comment by kaplun** [comment]
eheh yes

**Comment by kaplun** [comment]
Obsolete

**Pull request closed without merging**
