### PR TITLE
theme: MathJax fix

### PR DESCRIPTION
**Pull request by jacenkow**
* Loads the config of MathJax iff the external source was loaded.

Signed-off-by: Grzegorz Jacenków <grzegorz.jacenkow@cern.ch>

### CODE REVIEW

**Comment by jacenkow** [comment]
Resolves #1025

**Comment by jacenkow** [comment]
`pkg_resources._vendor.packaging.markers.UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.`

¯\\_(ツ)_/¯

**Comment by jacenkow** [comment]
@jacquerie can you rerun Travis per favore?

**Comment by jacquerie** [comment]
Just so everybody gets a mail about this: PRs today are going to fail because of https://github.com/pypa/setuptools/issues/523.

**Pull request merged**
