### PR TITLE
Package rename from inspire to inspirehep

### PR DESCRIPTION
**Pull request by jalavik**
It would be nice to release the overlay on PyPi, e.g. in order to benefit from hosted docs on pythonhosted.org. However, `inspire` is a taken name on PyPi, so therefore `inspirehep` seems a better alternative. This branch aims to fix this.

In addition, the repository name `inspire-next` will eventually no longer be "next" and we can take this occasion to rename it to `inspirehep` as well.

- [x] fix imports everywhere
- [x] fix setup.py and config files
- [ ] update docs
- [ ] rename this repo to `inspirehep`
- [x] move all tests from `testsuite/` into `tests`
- [ ] make sure repo configuration files are up-to-date (e.g. pytest.ini etc if necessary)
- [ ] release 0.1.0 on PyPi
- [ ] deploy docs

@kaplun @jmartinm

### CODE REVIEW

**Comment by jacquerie** [comment]
:+1:

BTW, about step five, note that a few tests are in other folders:
```shell
$ ag -g testsuite
inspire/modules/deposit/testsuite/fixtures/hep_submission_form.json
inspire/modules/deposit/testsuite/test_hep_submission.py
inspire/modules/deposit/testsuite/__init__.py
inspire/modules/authors/testsuite/test_utils.py
inspire/modules/authors/testsuite/__init__.py
inspire/modules/citations/testsuite/test_citations.py
inspire/modules/citations/testsuite/__init__.py
inspire/base/testsuite/__init__.py
inspire/base/testsuite/js/feedback.spec.js
[...]
```
this PR would be a nice time to consolidate them in one place.

**Comment by kaplun** [comment]
> this PR would be a nice time to consolidate them in one place.

:+1:

**Comment by jalavik** [comment]
Travis is green, although coverage took a hit. We can sort that out post-merge though. Okay for merge? @jmartinm @kaplun @jacquerie 

The remaining open tasks can come in second PR.

**Comment by jacquerie** [comment]
NP about coverage, it was bloated anyways (`.coveragerc` did not contain some useful configuration). Now I'll go through the code.

**Comment by jacquerie** [comment]
LGTM, minus the pickle part. Coverage will decrease further in the next few days : )

**Comment by kaplun** [comment]
Thanks for this sprint! For me :shipit: !

**Comment by kaplun** [comment]
We'll fix any issue tomorrow :dancer:

**Pull request merged**
