### PR TITLE
global: elasticsearch in virtualenv

### PR DESCRIPTION
**Pull request by kaplun**
* Improves Procfile configuration of elasticsearch to take into
  consideration the current virtual environment, thus creating
  logs and indexes in the appropriate paths.

Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
@jalavik can you check it doesn't break on Mac? (I guess it should work as long as you use as well a virtualenv)

**Comment by jalavik** [comment]
@kaplun Cool. I will test it. You can rebase now to get CI :)

**Comment by kaplun** [comment]
Hi @jalavik, my PR was against `master-rc` but I see you have now upgraded `master`. Was this intended? I thought `master` had to reflect exactly what was running on production, while `master-rc` is where we are actively working on.

**Comment by jalavik** [comment]
@kaplun So we use `master` as the main development branch as production states are already covered in `qa` and `production` branches. 

`master-rc` was a short lived affair due to uncertainties with ES configuration. Those uncertainties do still exist but we had to move on.

**Comment by kaplun** [comment]
OK! Sorry for misunderstanding :+1:

**Comment by jalavik** [comment]
@kaplun No worries. All the different branches are quite confusing so I think we'll try to stay with `master` as much as possible. 

PS: This PR got closed as I know killed the `rc` branches. Damn.

**Comment by kaplun** [comment]
No problem: it's open in #355... and it's green! Kudos Jan!

**Pull request closed without merging**
