### PR TITLE
dojson: strip empty values

### PR DESCRIPTION
**Pull request by kaplun**
* Introduces new step in dojson.processors, to remove any empty
  value, i.e. anything corresponding to "", None, an empty list or
  an empty dictionary. 0s and False are not considered empty values.

Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
cc: @jmartinm, @ioannistsanaktsidis

**Comment by ioannistsanaktsidis** [comment]
@kaplun you can assign it to me, I will take care.

**Comment by ioannistsanaktsidis** [comment]
Sorry though it's an issue not a PR :P

**Comment by kaplun** [comment]
eheh :dancer:

**Comment by kaplun** [comment]
It's something I had in a separate PR since too much time. So here it is :+1:

**Comment by ioannistsanaktsidis** [comment]
:+1:

**Pull request merged**
