### PR TITLE
update HEP Ontology

### PR DESCRIPTION
**Pull request by fschwenn**

### CODE REVIEW

**Comment by ammirate** [comment]
@fschwenn can you add a bit of context, please?

**Comment by david-caro** [comment]
btw. I don't think invenio-classifier is able to handle multiple ontology files.

**Comment by fschwenn** [comment]
@ammirate The context is that DESY takes care of the HEP ontology. From time to time we update it. And that updated ontology is then also updated in INSPIRE.

**Comment by fschwenn** [comment]
@david-caro It's enough if classifier can handle on at a atime.

**Comment by david-caro** [comment]
I mean that it does not handle multiple files, not at the same time, not one after the other, so if we wan to use more than one ontology file, we will need to change it.

**Comment by fschwenn** [comment]
bibclassify had the ontology as an argument. Do you mean that in the classifier it is hard-coded?!

**Comment by david-caro** [comment]
yep, it's hardcoded in the configuration:
https://github.com/inspirehep/inspire-next/blob/master/inspirehep/config.py#L1162

**Comment by fschwenn** [comment]
but classifier accepts arguments, doesnt it?
https://github.com/inspirehep/inspire-next/blob/b0b9d015a494add095f03b95688b3228fceecbe6/inspirehep/modules/workflows/tasks/classifier.py#L67

**Comment by david-caro** [comment]
yep, but accepts only one, not a list

**Comment by fschwenn** [comment]
but that's fine - as I said, we need to call it with different onotologies (at different times), but only one per call

**Comment by david-caro** [comment]
Then we should change the classifier task to run multiple times, one for each file no?

**Comment by fschwenn** [comment]
see #2647

**Comment by david-caro** [comment]
:+1:

**Pull request closed without merging**
