### PR TITLE
config: missing env var override

### PR DESCRIPTION
**Pull request by david-caro**
* Override ACCOUNTS_SESSION_REDIS_URL conf key with the env var if
  available
* Update docker compose files to use it

Signed-off-by: David Caro <david.caro@cern.ch>

### CODE REVIEW

**Comment by mihaibivol** [comment]
Thanks :)

**Comment by david-caro** [comment]
@kaplun this is ready to merge, ok for you?

**Comment by jacquerie** [comment]
LGTM, except a very trivial nit: we usually add a space after the colon in the commit message title.

**Comment by david-caro** [comment]
@jacquerie Is changing the title here enough? I'm not that familiar with github

**Comment by jacquerie** [comment]
Sadly not: you'll need a `git commit --amend`. BTW, this also needs a rebase on top of current master.

**Comment by david-caro** [comment]
Sorry for the noise, now it should be ok

**Pull request merged**
