### PR TITLE
global: upgrade to ES5

### PR DESCRIPTION
**Pull request by ammirate**
## Tests:

Test | Outcome
-- | --
workflow errors when matched against WF in ERROR | OK (workflow in ERROR)
article submission form blocks if submission WF has it (by arXiv) | OK (displays a banner)
article submission form blocks if submission WF has it (by DOI, case insensitive) | OK (displays a banner)
article submission form blocks if record is in inspire  for arXiv | OK (displays a banner)
article submission form blocks if record is in inspire  for DOI (case insensitive) | OK (displays a banner)
literature submission card shows literature submissions | OK (shows)
arxiv harvests card shows arxiv harvests | OK (shows)
arxiv updates card shows arxiv update | OK (shows)
publisher harvests card shows publisher harvest | OK (shows)
publisher updates card shows publisher update | OK (shows)
if `journal_coverage=full` reject button opaque in holdingpen | OK (button opaque)
facet 'filter by action' shows 'Matching' for records with 'extra_data._action=match_approval' | OK
filters for status, source, subject, collections correctly narrow the search | OK (results change according to the chosen facet)
author submitted from the form shows in the 'New Authors' card' | OK
sorting works for relevance prediction (asc and desc) | OK
best match works for sorting | OK (results are in different order than chronological, seemingly in order of relevance)
searching by title works for literature workflows | FAIL (not defined in the mapping: non-dynamic)
searching by eprint number works for literature | OK
searching by name works for author workflows | FAIL (not defined in the mapping: non-dynamic)
editor autocompletes institutions | OK
editor autocompletes experiments | OK
fuzzy match by submission matching the title and authors or a record | OK (suggestion shows)
fuzzy match by desy harvest matching a record | OK (suggestion shows)
affiliation completion works on literature submission form | OK
reference matches are the same as before | OK (same results for workflows: 1104836, 1104832, 1104420, 1104738, 1104496)

## Checklist:

- [ ] I have all the information that I need (if not, move to `RFC` and look for it).
- [ ] I linked the related issue(s) in the corresponding commit logs.
- [ ] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [ ] My code follows the code style of this project.
- [ ] I've added any new docs if API/utils methods were added.
- [ ] I have updated the existing documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ammirate** [comment]
This supersedes https://github.com/inspirehep/inspire-next/pull/3514

**Comment by szymonlopaciuk** [comment]
ci test please

**Comment by szymonlopaciuk** [comment]
ci test please

**Comment by szymonlopaciuk** [comment]
ci test please

**Comment by michamos** [comment]
Could you also check the number of matched references on ES5 for a harvest to make sure the reference matcher works correctly?

**Comment by szymonlopaciuk** [comment]
Superseded by #3548

**Comment by david-caro** [comment]
This was merged...

**Pull request closed without merging**
