### PR TITLE
Production sync back on track

### PR DESCRIPTION
**Pull request by jalavik**
This puts us back on track with the INSPIRE production sync.

It adds a workflow task that can store records into the system with custom record IDs.

### CODE REVIEW

**Comment by jmartinm** [comment]
Nice, for new records added in INSPIRE, will we keep the same record id in labs with this code?

**Comment by jalavik** [comment]
@jmartinm Yeah, so records with an existing `control_number` will keep it upon the initial import. Any additional updates will also update the records.

**Comment by jmartinm** [comment]
I see. Looking at the code seems good to me.

**Comment by jalavik** [comment]
Merged. Note that for record updates to index properly, we depend on these fixes: https://github.com/inveniosoftware/invenio-collections/pull/5 and https://github.com/inveniosoftware/invenio-records/pull/28

**Pull request merged**
