### PR TITLE
celery: bump to 4.2.0

### PR DESCRIPTION
**Pull request by ammirate**
Signed-off-by: Antonio Cesarano <cesarano2607@gmail.com>

### CODE REVIEW

**Comment by michamos** [comment]
what about https://github.com/inveniosoftware/invenio-celery/issues/53 ?

**Comment by ammirate** [comment]
That's what I wanted to check :point_up:

**Comment by ammirate** [comment]
Maybe we can downgrade to 4.0.2? The timezone bug is really annoying

**Comment by michamos** [comment]
> Maybe we can downgrade to 4.0.2? The timezone bug is really annoying

I know, we investigated it back when we upgraded from celery 3, but there were real blockers in 4.0.*, so we chose the lesser evil.

**Comment by ammirate** [comment]
Close this for now.

**Pull request closed without merging**
