### PR TITLE
global: es5 support

### PR DESCRIPTION
**Pull request by szymonlopaciuk**
# Changes

- suggestions
- queries
- mappings
- align with API changes in elasticsearch and elasticsearch_dsl clients
- receivers: remove empty string from name_suggest
- services.yml: use inspirehep/elasticsearch5 image

INCOMPATIBLE: this breaks the backwards compatibility with ES2

## Checklist:

- [x] I have all the information that I need (if not, move to `RFC` and look for it).
- [x] I linked the related issue(s) in the corresponding commit logs.
- [x] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [x] My code follows the code style of this project.
- [x] I've added any new docs if API/utils methods were added.
- [x] I have updated the existing documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by szymonlopaciuk** [comment]
ci test please

**Comment by szymonlopaciuk** [comment]
Superseeds #3527

**Comment by szymonlopaciuk** [comment]
ci test please

**Comment by ammirate** [comment]
ci test please

**Comment by david-caro** [comment]
ci test please

**Comment by david-caro** [comment]
ci merge please

**Pull request merged**
