### PR TITLE
travis: add beard to dependencies

### PR DESCRIPTION
**Pull request by jalavik**
Continuation from #370

### CODE REVIEW

**Comment by glouppe** [comment]
I am not sure you want to install Anaconda for testing Inspire. Couldnt you rather have a normal build inside a Docker so that Numpy and Scipy compilations (along with all other depencies) are done once and for all? CC: @eamonnmag

**Comment by jalavik** [comment]
@glouppe Yeah, might be the easiest in the end.

**Comment by eamonnmag** [comment]
Yes, I think this is the way things should be done in future.

**Comment by jalavik** [comment]
Actually it's passing nicely now. So I will merge it for now. Then we work on Docker integration.

**Comment by glouppe** [comment]
Note that conda environments usually dont play that well with virtualenvs... I think the build is mixing both now, which may not be a good idea.

**Comment by jalavik** [comment]
Superseded by #372

**Pull request closed without merging**
