### PR TITLE
HEP ingestion and Holding Pen integration fixes

### PR DESCRIPTION
**Pull request by jalavik**
Current WIP.

Depends on https://github.com/inspirehep/invenio-workflows/pull/3

### CODE REVIEW

**Comment by jalavik** [comment]
@jmartinm @kaplun Updated. If this passes the Travis build I will merge. Not fixing the Quantified stuff at this moment.

**Comment by kaplun** [comment]
I don't understand why we don't have coveralls though :stuck_out_tongue:

**Comment by jalavik** [comment]
@kaplun True, we can add it. It is only displayed on the front page for now. There is room for improving the coverage I believe as there is probably code that is (a) dead, (b) repeated and (c) without testing obviously, in order of difficulty to improve :dancer:

**Comment by kaplun** [comment]
BTW coverage improved with your PR :wink:

**Pull request merged**
