### PR TITLE
tools: rewrite authorlist

### PR DESCRIPTION
**Pull request by michamos**
## Description

Integrates the new authorlist tool by @ksachs. The biggest difference as far as the API is concerned is that it now produces warnings (in `warnings` key of the returned dict) for non-fatal ambiguities, besides exceptions for fatal errors as previously. @harunurhan these warnings should be shown in the editor.

## Related Issue

Integrates and closes #3054.

## Checklist:

- [x] I have all the information that I need (if not, move to `RFC` and look for it).
- [x] I linked the related issue(s) in the corresponding commit logs.
- [x] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [x] My code follows the code style of this project.
- [x] I've added any new docs if API/utils methods were added.
- [x] I have updated the existing documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by bavaria95** [comment]
ci test please

**Comment by michamos** [comment]
@ksachs this is how it looks now
screenshot-2018-1-11 format author strings to marc21 - inspire labs

**Comment by ksachs** [comment]
Nice!
I guess it shows one item-bullet for each line in the warnings string.

**Comment by michamos** [comment]
No, I changed the warnings from a string to a list of strings, which makes it easier to display afterwards.

**Pull request merged**
