### PR TITLE
Institute detailed page

### PR DESCRIPTION
**Pull request by jmartinm**

### CODE REVIEW

**Comment by jmartinm** [comment]
Takes over from https://github.com/inspirehep/inspire-next/pull/1145

inspire-inst

**Comment by eamonnmag** [comment]
Awesome!

**Comment by kaplun** [comment]
This is indeed great! As we mused IRL (and partially with Salvatore), would be great if:
* [ ] List of papers is moved above other stats
* [ ] Sorted by number of papers
* [ ] Clearly understand if we consider papers from people *currently* at the given institutions (so Institute -> People -> papers) Vs. Papers with authors affiliated at the given institution
* [ ] Boxes should be memoized 
* [ ] While we are basing this on ES rather than Neo4J, we should then make use of nested documents (in particular to search for all the signatures which have been made at a given institute and then be able to group by that author)

**Comment by jmartinm** [comment]
> Clearly understand if we consider papers from people currently at the given institutions (so Institute -> People -> papers) Vs. Papers with authors affiliated at the given institution

So after nesting authors in `Literature` what I am doing is getting all authors that wrote a paper while being affiliated at the institution and counting the number of papers they wrote (at the institution).

So it is historical data (not current) which has the benefit of only involving querying `Literature` and also our `current` status is usually not very up-to-date.

**Pull request merged**
