### PR TITLE
Facet year range

### PR DESCRIPTION
**Pull request by jmartinm**
Pending merge of https://github.com/inspirehep/inspire-next/pull/1255
Pending release of https://github.com/inveniosoftware/invenio-search-js in npm

### CODE REVIEW

**Comment by jacquerie** [comment]
This looks like it could be resurrected and merged. Things it mentioned being necessary to do before were done, so...

**Comment by jmartinm** [comment]
I will take care of rebasing and making it work again.

**Comment by jmartinm** [comment]
This is ready.

**Comment by jmartinm** [comment]
After https://github.com/inspirehep/inspirehep-search-js/pull/17 is merged

**Pull request merged**
