### PR TITLE
forms: fix orcid validation after API update

### PR DESCRIPTION
**Pull request by szymonlopaciuk**
## Related Issue
https://sentry.inspirehep.net/inspire-sentry/inspire-qa/issues/42234/

## Checklist:

- [ ] I have all the information that I need (if not, move to `RFC` and look for it).
- [ ] I linked the related issue(s) in the corresponding commit logs.
- [ ] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [ ] My code follows the code style of this project.
- [ ] I've added any new docs if API/utils methods were added.
- [ ] I have updated the existing documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by szymonlopaciuk** [comment]
Superseded by #3236

**Comment by szymonlopaciuk** [comment]
Misunderstood, reopening for now

**Comment by jacquerie** [comment]
I think we can close this, I will cherry-pick this commit from the `prod` branch when it's tested on QA / deployed on PROD.

**Comment by david-caro** [comment]
@jacquerie just making sure, you should rebase master on top of prod, not cherry pick (so the commit hash on both branches is the same).

**Pull request closed without merging**
