### PR TITLE
Link DOIs to preferred resolver

### PR DESCRIPTION
**Pull request by katrinleinweber**
## Description
The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Accordingly, this PR updates static DOI links and the code that generates new ones.

I'm unsure whether to include the tests, but to get the CI results, I'll do it for now and if necessary, revert those changes.

## Related Issue
https://github.com/inspirehep/inspirehep-search-js/pull/66

## Motivation and Context
see `Description` above

## Checklist:

- [ ] I have all the information that I need (if not, move to `RFC` and look for it).
- [x] I linked the related issue(s) in the corresponding commit logs.
- [x] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [x] My code follows the code style of this project.
- [x] I've added any new docs if API/utils methods were added.
- [x] I have updated the existing documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed. *relying on the CI here*

### CODE REVIEW

**Comment by katrinleinweber** [comment]
@david-caro The bot seems over-eager ;-)

**Comment by turtle321** [comment]
Hello Katrin, I closed this PR as a cleanup. We are about to release a new version of the UI and we will include this change there.

**Comment by katrinleinweber** [comment]
OK, good luck :-)

**Comment by katrinleinweber** [comment]
Dear @turtle321, there have been [several releases](https://github.com/inspirehep/inspire-next/releases), but still [many old DOI links, and even some code that generates new DOI hyperlinks](https://github.com/inspirehep/inspire-next/search?q=dx.doi&unscoped_q=dx.doi).

Shall I update this PR and send it again?

**Pull request closed without merging**
