### PR TITLE
search: removes unused code from search_results.js

### PR DESCRIPTION
**Pull request by ioannistsanaktsidis**
Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

### CODE REVIEW

**Comment by jalavik** [comment]
Thanks @ioannistsanaktsidis. Can you rebase on latest master (for CI).

**Comment by ioannistsanaktsidis** [comment]
@jalavik rebased succesfully!

**Comment by ioannistsanaktsidis** [comment]
The thing is that the PR is in the master-rc, do you want me to close it and create a new one to master?

**Comment by jalavik** [comment]
Ah yeah. That would be good :-)

**Pull request closed without merging**
