### PR TITLE
dojson: fixes doi mapping

### PR DESCRIPTION
**Pull request by ioannistsanaktsidis**
Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

### CODE REVIEW

**Comment by jmartinm** [comment]
We are missing some things here:

* For DOIs, the source needs to be added (subfield $$9)
* For other types of identifiers ([see here](https://github.com/inspirehep/inspire-next/blob/master/inspire/dojson/current_marcxml_usage/hep.txt#L488)) we would be dropping them. After talking with Annette and Alexander I think we should add a new field to the schema:

```json
"persistent_identifiers": {
            "uniqueItems": true,
            "items": {
                "type": "object",
                "properties": {
                    "source": {
                        "type": "string",
                        "description": "Provenance of the persistent identifier",
                    },
                    "type": {
                        "type": "string",
                        "title": "Type of persistent identifier"
                    },
                    "value": {
                        "type": "string",
                        "title": "Value of the persistent identifier"
                    }
                },
                "title": "Persistent Identifier"
            },
            "type": "array",
            "title": "Persistent Identifiers"
```

**Comment by jalavik** [comment]
#400 is touching the doi field as well, but I can sort out the conflict if this is merged first.

**Comment by ioannistsanaktsidis** [comment]
for the persistent_identifiers will we map it like:
@hep.over('persistent_identifiers', '^024[1032478_][10_]')
@utils.for_each_value
@utils.filter_values
def persistent_identifiers(self, key, value):
    """Other Standard Identifier."""
    if value.get("2").lower() != "doi":
        return {
            'value': value.get('a'),
            'source': value.get('9'),
            'type': value.get('2')
        }

**Comment by jmartinm** [comment]
@ioannistsanaktsidis 

Yes, that looks right.

**Comment by ioannistsanaktsidis** [comment]
@jmartinm  I have just amended the commit.

**Comment by jmartinm** [comment]
Ok, thanks, you can sync with @jalavik and the PR https://github.com/inspirehep/inspire-next/pull/400

**Comment by ioannistsanaktsidis** [comment]
Cool!

**Comment by jalavik** [comment]
These fixes are now incorporated in #400

**Pull request closed without merging**
