### PR TITLE
holdingpen: no indexing of classifier_results

### LINKED ISSUE #2456: Invenio-classifier using keywords a key in dictionary
## Current Behavior
`invenio-classifier` is outputting many information in a pythonic way. Unfortunately the structure used is:
```python
{'categories': {'ATLAS': 'HEP',
  'CERN LHC Coll': 'HEP',
  [...]
  'wave function': 'HEP',
  'weak coupling': 'HEP'},
 'complete_output': {'acronyms': {},
  'author_keywords': [],
  'composite_keywords': {'axion: decay constant': {'details': [18, 2],
    'numbers': 1},
   'coupling: Yukawa': {'details': [8, 1], 'numbers': 1},
   'dimension: 2': {'details': [5, 58], 'numbers': 1},
   'electroweak interaction: standard model': {'details': [10, 2],
    'numbers': 1},
   'energy: ground state': {'details': [26, 2], 'numbers': 2},
   [...]
   'transformation: unitarity': {'details': [12, 3], 'numbers': 1}},
  'core_keywords': {'ATLAS': 1,
   'CERN LHC Coll': 6,
   [...],
   'string model': 2,
   'supersymmetry': 3},
  'field_codes': {'g': 'cosmological constant'},
  'single_keywords': {'ATLAS': 1,
   'Chern-Simons number': 14,
   [...]
   'toy model': 1,
   'translation': 3,
   'wave function': 1}}}
```

Unfortunately this is using the keyword as key in a dictionary, which is then passed as such to ES, that tries to create a guessed mapping for each of them.

## Expected Behavior
Keywords should be passed as list of tuples possibly sorted by their importance.

Note: this was partially addressed already in: https://github.com/inveniosoftware-contrib/invenio-classifier/pull/25

### PR DESCRIPTION
**Pull request by kaplun**
- [x] I have all the information that I need (if not, move to `RFC` and look for it).
- [x] I linked the related issue(s) in the corresponding commit logs.
- [x] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [x] My code follows the code style of this project.
- [x] I've added any new docs if API/utils methods were added.
- [ ] I have updated the existing documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

The output of `invenio-classifier`, currently put inside
`obj.extra_data['classifier_results']` is not in a ES-friendly
structure, due to using keywords as key in a dictionary (rather than
as value).

Temporary fixes this issue by disabling entirely indexing of
`classifier_results` in holdingpen.
(closes #2456)

Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
cc: @jmartinm @jacquerie

**Comment by kaplun** [comment]
@jacquerie I am disabling only `classifier_results` because the other ML fields are well structured and are very likely offering searchable information (e.g. `categories_prediction` is definitively useful for focusing on a given category)

**Comment by jacquerie** [comment]
I know that I originally proposed to do this, but if @ksachs is already searching on this field then we need to fix rather than break this feature for her...

**Comment by kaplun** [comment]
Yeah I'll try my best. But `invenio-classifier` is only slightly less convoluted than `refextract`. Let's see what I can do.

**Comment by jacquerie** [comment]
> Yeah I'll try my best. But `invenio-classifier` is only slightly less convoluted than `refextract`. Let's see what I can do.

But we could just take the output of `invenio-classifier` and adapt it in the task, like we did in https://github.com/inspirehep/inspire-next/pull/2342 to solve a similar problem.

We should be using these legacy packages as much as possible as blackboxes, after all.

**Comment by kaplun** [comment]
Yeah too late :smile: I am almost done amending it. It's for the good of ecology.

**Comment by kaplun** [comment]
It was disturbing my sense of symmetry to amend `author_keywords` on `invenio-classifier` side, and all other properties on `inspire-next` side.

**Pull request closed without merging**
