### PR TITLE
WIP demosite: improved demo records

### PR DESCRIPTION
**Pull request by kaplun**
* Improves the demo records by really including citing and cited
  papers.

* Uses preferentially recent CORE records.

* Adds demo-records-links.txt, a description file containing the list
  which records+MARC field points to which other record.

* Filter out invalid links (i.e. those for which the referred record
  hasn't been included in the demo records set).

Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
@nikpap, @jmartinm this new set should contain many more (and only) valid links.

**Comment by nikpap** [comment]
@kaplun that's great! Going to test as soon as it's merged.
`inveniomanage migrator populate -t marcxml -f pwd/inspire/demosite/data/demo-records.xml --force` still needed to load them, right?

**Comment by kaplun** [comment]
Exactly.

**Comment by kaplun** [comment]
@ioannistsanaktsidis, @jmartinm, @jalavik help! It looks like we need to support multiple languages! See: https://github.com/kaplun/inspire-next/commit/d6c76500e881aafb8235df8d91d7d82f280eb1b0

I have tried amending a bit the code, but I fear I am doing a mess :smile:

**Comment by jalavik** [comment]
You might need to also amend dojson for the literature submission and bibfield conversion as well:
```
inspire/modules/deposit/dojson/fields/literature.py:@literature.over('language', '^language$')
inspire/modules/deposit/dojson/fields/literature.py:def language(self, key, value):
inspire/modules/deposit/dojson/fields/literature.py:    languages = [("en", "English"),
inspire/modules/deposit/dojson/fields/literature.py:        return unicode(dict(languages).get(value))
...
inspire/modules/deposit/workflows/literature.py:        if metadata.get("language") == "oth":
inspire/modules/deposit/workflows/literature.py:            if form_fields.get("other_language"):
inspire/modules/deposit/workflows/literature.py:                metadata["language"] = form_fields["other_language"]
...
inspire/modules/workflows/dojson/fields/bibfield.py:def language(self, key, value):
inspire/modules/workflows/dojson/fields/bibfield.py:    """Get language from object."""
inspire/testsuite/test_bibfield.py:    def test_language(self):
inspire/testsuite/test_bibfield.py:        """Test if language is created correctly"""
inspire/testsuite/test_bibfield.py:            self.bibfield_json['language'],
inspire/testsuite/test_bibfield.py:            self.record['language']
```

**Comment by jmartinm** [comment]
Merged https://github.com/inspirehep/inspire-next/pull/505

**Pull request closed without merging**
