### PR TITLE
demosite: brand new demo records

### PR DESCRIPTION
**Pull request by kaplun**
* Introduces new demo records by using the new script:
  inspirehep/inspire-scripts/utility/generate_demo_records.py.

* Contains the 10 most cited hep papers, 10 core books, theses,
  proceedings, notes, corresponding cited papers, 10 citing papers
  for each paper, 10 collaboration papers.

* Contains all the HepNames record referred across the papers.

* Expands the MARCXML of the publications, by adding 2 new subfields
  in the 100 and 700 tags:
  $x: containing the record ID of the author HepName
  $y: containing 1 if the given ID is claimed/checked, 0 otherwise

Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by jmartinm** [comment]
So it seems the blocker for merging these records is being able to workaround hardcoding the record ids.

This is necessary for the demo site in order to have correct links among records.

**Comment by jmartinm** [comment]
By the way, how are we going to do so that the demo records contain all the references and citations in the JSON so that it is ready to be displayed?

**Comment by kaplun** [comment]
> By the way, how are we going to do so that the demo records contain all the references and citations in the JSON so that it is ready to be displayed?

At the moment, these are available in the MARCXML as part of $0 field of each reference. Of course all those references that currently don't have an explicit link in the MARCXML will not have a valid link in JSON.

**Comment by kaplun** [comment]
@jalavik, @jmartinm, @Panos512 the new demo records are now passing, but there are some failures in the unittests due to the fact that record IDs are no longer the first few small records identifiers.

E.g.
```python
=================================== FAILURES ===================================
________________ CitationsTests.test_citations_references_empty ________________
self = <inspire.modules.citations.testsuite.test_citations.CitationsTests testMethod=test_citations_references_empty>
    def test_citations_references_empty(self):
        """Test if record is working corectly when all citations are deleted"""
        from invenio_records.api import get_record
        rec8 = get_record(8)
>       self.assertEqual(rec8.get("references_id"), [])
E       AttributeError: 'NoneType' object has no attribute 'get'
inspire/modules/citations/testsuite/test_citations.py:97: AttributeError
_____________ CitationsTests.test_citations_references_nonexistant _____________
self = <inspire.modules.citations.testsuite.test_citations.CitationsTests testMethod=test_citations_references_nonexistant>
    def test_citations_references_nonexistant(self):
        """Test if record is working corectly without any citations"""
        from invenio_records.api import get_record
        rec3 = get_record(3)
>       self.assertEqual(rec3.get("references_id"), None)
E       AttributeError: 'NoneType' object has no attribute 'get'
inspire/modules/citations/testsuite/test_citations.py:91: AttributeError
_______________ CitationsTests.test_citations_references_updated _______________
self = <inspire.modules.citations.testsuite.test_citations.CitationsTests testMethod=test_citations_references_updated>
    def test_citations_references_updated(self):
        """Test if record is populated corectly with new citations"""
        from invenio_records.api import get_record
        rec1 = get_record(1)
>       self.assertEqual(rec1.get("references_id"), [2, 3])
E       AttributeError: 'NoneType' object has no attribute 'get'
inspire/modules/citations/testsuite/test_citations.py:85: AttributeError
```

I am thinking whether in the `setUp()` phase we should allocate 10 empty records with IDs from 1 to 10 , and delete those upon `tearDown()` but this seems a bit clumsy. Any better idea?

**Comment by Panos512** [comment]
Yeah this could be done. Or we could add them to the end (from the last id and on) so that they will not collide with useful data.

**Comment by jalavik** [comment]
Another way could also be to change the mock data to work with the recids of the demo records. These are loaded before tests are run, so it could work. Otherwise setup indeed needs to allocate the appropriate records.

**Comment by kaplun** [comment]
This depends on https://github.com/inspirehep/inspire-next/issues/426

**Comment by kaplun** [comment]
@jalavik this is still not mergable because of tests failing because of invenio-records thingy.

**Comment by jmartinm** [comment]
Did a small modification here and the tests are passing https://github.com/inspirehep/inspire-next/pull/460

**Pull request merged**
