### PR TITLE
config: physics.data-an

### PR DESCRIPTION
**Pull request by kaplun**
* Introduces new physics.data-an mapping to Data Analysis and
  Statistics.

Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by jacquerie** [comment]
Well, looks straightforward enough... : )

LGTM

**Comment by jacquerie** [comment]
...and yet it fails: https://travis-ci.org/inspirehep/inspire-next/jobs/146356553#L1546

**Comment by kaplun** [comment]
Agh! And the failing record is: https://inspirehep.net/record/1324783 which precisely is about the field I am changing.

**Comment by jacquerie** [comment]
Sync and :ship:?

**Comment by kaplun** [comment]
Yep!

**Comment by kaplun** [comment]
There we go!

**Pull request merged**
