### PR TITLE
migrator: only set prod record as failed when it's there

### LINKED ISSUE #3121: UnboundLocalError: local variable 'prod_record' referenced before assignment
https://sentry.inspirehep.net/inspire-sentry/prod/issues/2095/

```
UnboundLocalError: local variable 'prod_record' referenced before assignment
  File "inspirehep/modules/migrator/tasks.py", line 184, in continuous_migration
    skip_files=skip_files,
  File "inspirehep/modules/migrator/tasks.py", line 371, in migrate_and_insert_record
    prod_record.valid = False

UnboundLocalError: local variable 'prod_record' referenced before assignment
```

### PR DESCRIPTION
**Pull request by david-caro**
- [x] I have all the information that I need (if not, move to `RFC` and look for it).
- [x] I linked the related issue(s) in the corresponding commit logs.
- [x] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [x] My code follows the code style of this project.
- [x] I've added any new docs if API/utils methods were added.
- [x] I have updated the existing documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Fixes #3121

Signed-off-by: David Caro <david@dcaro.es>

### CODE REVIEW

**Comment by ammirate** [comment]
Perhaps adding some tests would make this function more stable, we already did a quick fix for this... wdyt? :/

**Comment by david-caro** [comment]
That it needs refactoring, I think it tries to do too many things, and it strange ways (keeping the error var around, and such). I'd create another PR for it.

**Comment by ammirate** [comment]
So it's not worth neither adding the record that triggered this unknown behavior as a test? That would be at least something.

**Comment by david-caro** [comment]
That in specific will not help, as it will stop triggering the error as soon as dojson is fixed. To test this, I think that the strategy should be mocking the marcxml2record and forcing the throw of an exception there. Also for the record_insert_or_replace, and then make sure that it handles it gracefully.

**Comment by david-caro** [comment]
btw. if you agree, I'll merge, this is hiding some errors (as it shadows the original error).

**Comment by ammirate** [comment]
"Move fast, break things"

**Pull request merged**
