### PR TITLE
facets: fixes search bug in facets

### PR DESCRIPTION
**Pull request by ioannistsanaktsidis**
* Addresses #500.

Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

### CODE REVIEW

**Comment by ioannistsanaktsidis** [comment]
@jmartinm this one is for this bullet: 
```
If you first click a facet and then make a search the facets should clear again(?). E.g you click Adinolfi, Marco and you get 5 results. If you make a search afterwards it should reset the filter I guess. 
```

**Comment by nikpap** [comment]
@ioannistsanaktsidis please not that in the copyright, `Invenio` needs to be changed to `INSPIRE`.

What's the difference with https://github.com/inspirehep/invenio-search/blob/master/invenio_search/templates/search/form/form_base.html ?

**Comment by ioannistsanaktsidis** [comment]
I removed this line from the template  <input type="hidden" name="
post_filter" value="{{request.args.get('post_filter', '')}}"> which we dont
need in the overlay.

**Comment by jmartinm** [comment]
Did you make sure that removing the input field does not have any side effect or create some error in the facets JS code? https://github.com/inveniosoftware/invenio-search/blob/master/invenio_search/static/js/search/search.js#L97

**Comment by ioannistsanaktsidis** [comment]
I checked multiple combinations and I can't reproduce any problem. Also the
console is clear.

2015-11-12 14:07 GMT+01:00 Javier Martin Montull <notifications@github.com>:

**Comment by ioannistsanaktsidis** [comment]
I will close this PR as we are going to take care the problem in the form.js file.

**Pull request closed without merging**
