### PR TITLE
migrator: faster citation count implementation

### PR DESCRIPTION
**Pull request by kaplun**
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
@jacquerie this implementation should not take 1.5 days to compute :dancer:

**Comment by jacquerie** [comment]
:+1:

The idea looks ok, but I think there's more to fix in this function. I will take care of merging this myself.

**Comment by kaplun** [comment]
What do you want to fix? It works for me...

**Comment by jacquerie** [comment]
> What do you want to fix?

The logic from line 271 to 281 (it can be greatly simplified).

**Pull request closed without merging**
