### PR TITLE
FIX: properly map category tokens to feature indices

### PR DESCRIPTION
**Pull request by glouppe**
@jalavik This should fix the bug :)

### CODE REVIEW

**Comment by jalavik** [comment]
@glouppe Thanks! I will give it a shot.

There is a PEP8 issue and can you slightly amend the commit log message to fit with the rest, e.g. using the module name. Like `predicter: category tokens to feature indices mapping fix`

**Comment by glouppe** [comment]
I updated the commit message, but I dont see any pep8 or pe257 issue.

**Comment by glouppe** [comment]
All fixed.

**Comment by jalavik** [comment]
@glouppe Thanks. I tested locally with the old model and it works now!

Just a small question. Here are the results from one run:
```
{'all_scores': array([-0.91960737, -1.03013271,  0.85721623]),
   'decision': u'Rejected',
   'max_score': 0.85721623310819428,
   'top_core': [(u'ph', 0.12853516726127312),
    (u'astro', 0.11927523070188641),
    (u'r_', 0.072433667171686936),
    (u'm_', 0.068153613820838718),
    (u'pm0', 0.065103747938550074),
    (u'double', 0.038748160710446115),
    (u'sim', 0.033121158410263168),
    (u'masses', 0.032529265898928884),
    (u'binaries', 0.028297702632627979),
    (u'stars', 0.026580451779565344)],
   'top_noncore': [(u'astro', 1.1875895999179999),
    (u'odot', 0.071488569345058969),
    (u'epic', 0.038501615175598684),
    (u'dwarf', 0.037032506647669508),
    (u'days', 0.035358028632533782),
    (u'spectroscopic', 0.034569685228290174),
    (u'ratios', 0.034272233596507704),
    (u'comprised', 0.027041021286810487),
    (u'secondary', 0.023692572311404116),
    (u'stellar', 0.022307574467856122)],
   'top_rejected': [(u'sr', 2.0016789082872917),
    (u'eclipsing', 0.076203715373205805),
    (u'pm0', 0.063772929231151174),
    (u'ratios', 0.032272571347064828),
    (u'lined', 0.023286956923488904),
    (u'brown', 0.019599986722229634),
    (u'revealed', 0.017899819241616734),
    (u'stellar', 0.017454908047898857),
    (u'k2', 0.016623555162131858),
    (u'hierarchical', 0.01531998919319456)]},
```

Notice that the top words for `noncore` and `core` are positive values while the score is ultimately negative. Does this mean that we get the top words sorted with the positive impact at the top and the negatives are at the other end of the list (even if they count for more)? Or is this somehow related to the initial bias values?

**Comment by glouppe** [comment]
Yes, the top words may not always explain the overall decision. 

Things to always keep in mind:
- the default score for core and non-core is around -1.
- the default score for rejected is around +0.85.

This means you need to accumulate a significant number of core/non-core keywords in order to counter-balance the default rejection decision. 

> Does this mean that we get the top words sorted with the positive impact at the top and the negatives are at the other end of the list (even if they count for more)? 

Yes, top words are simply sorted by values in descending order, hence these rankings only show you one side of the decision.

**Comment by jalavik** [comment]
Thanks, merged as 906ff73

**Pull request closed without merging**
