### PR TITLE
format: show more abstract in HEP collection records

### PR DESCRIPTION
**Pull request by nikpap**
* Implements the 'show more' and 'show less' abstract in pure CSS.

* Resolves an issue with HEP detailed record abstract not displaying correctly.

Signed-off-by: Nick Papoutsis <admin@nils.gr>

### CODE REVIEW

**Comment by jmartinm** [comment]
This PR has not been updated since we spoke IRL about the changes needed (like inline `Show more`) right?

**Comment by nikpap** [comment]
@jmartinm I've updated this PR to reduce the size of text and removed the arrows. Placing it on the same line would require a completely different approach with JS. Ss far as I researched, that can't be done simply with CSS. Here's what it currently looks like:

capture d ecran 2015-11-19 a 10 50 54

capture d ecran 2015-11-19 a 10 51 01

**Comment by jmartinm** [comment]
Did you give a try to this? http://stackoverflow.com/questions/26002974/css-text-ellipsis-including-more-link

**Comment by nikpap** [comment]
I tried the solutions given in the thread, but none seem to currently work. It seems like the only way to have the "show more" text inline would be to use javascript.

**Comment by jmartinm** [comment]
Alright, I will merge this one for the moment.

An alternative in JS is to use the `readmore` library (which we already install anyway)

**Pull request merged**
