### PR TITLE
records.receivers: refactor

### PR DESCRIPTION
**Pull request by david-caro**
* Moved the 'populate' and 'is_' methods to utils, leaving only the receivers in the receivers module.
* Removed unneeded params from the 'populate' methods.
* Rename enhance_after_index to enhance_before_index, as it runs before indexing.
* Explicitly separate the 'populate' methods used for each record type in the enhance_after_index.

- [x] I have all the information that I need (if not, move to `RFC` and look for it).
- [x] I linked the related issue(s) in the corresponding commit logs.
- [x] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [x] My code follows the code style of this project.
- [x] I've added any new docs if API/utils methods were added.
- [x] I have updated the existing documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by michamos** [comment]
isn't it used to sort by date in the search results?

**Comment by david-caro** [comment]
Yep, the comment is a bit misleading, I'll rephrase.

**Comment by david-caro** [comment]
ci merge please

**Comment by david-caro** [comment]
ci merge please

**Pull request merged**
