### PR TITLE
dojson: ignore double longitudes

### PR DESCRIPTION
**Pull request by jacquerie**
Now that https://github.com/inspirehep/inspire/issues/170 was properly solved on Legacy data we can start ignoring this error on Nightly.

### CODE REVIEW

**Comment by kaplun** [comment]
@jacquerie Note that that unfortunately it worked partially so in the dojson rule, you still have to skip all the single longitudes

**Comment by kaplun** [comment]
To be more clear: we currently have records with a field having just a longitude, and a field having a longitude and a latitude.

**Comment by jacquerie** [comment]
> To be more clear: we currently have records with a field having just a longitude, and a field having a longitude and a latitude.

Ok. I added a commit that doesn't produce a location if it isn't complete with both a latitude and a longitude.

**Comment by david-caro** [comment]
LGTM

**Pull request merged**
