### PR TITLE
WIP tests: more integration tests

### PR DESCRIPTION
**Pull request by jacquerie**
Converts views unit tests to integration tests, and adds a test to ensure that visiting a detailed record view doesn't raise an exception.

### CODE REVIEW

**Comment by jacquerie** [comment]
Requires #1054, and maybe a lot more tests from #918.

**Comment by jacquerie** [comment]
Coverage so low because it ran into https://github.com/lemurheavy/coveralls-public/issues/487.

**Comment by jmartinm** [comment]
👍  Note that you can now rebase and remove the commit that pins the libraries as it was merged this morning into `invenio3`

**Comment by jacquerie** [comment]
Superseded by #1088.

**Pull request closed without merging**
