### PR TITLE
config: use the right capitalization for LArSoft

### PR DESCRIPTION
**Pull request by jacquerie**
## Description:
Note that this commit requires to recreate the `collection` table in
production, otherwise the records in the LArSoft special collection
would be assigned to a no longer existing collection.

Because of this I'm not going to merge it now, as deployments are
still blocked, and it wouldn't make sense to pile up more manual ops.

CC: @david-caro @kaplun @jmartinm 

## Checklist:
- [x] I have all the information that I need (if not, move to `RFC` and look for it).
- [ ] I linked the related issue(s) in the corresponding commit logs.
- [x] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [x] My code follows the code style of this project.
- [ ] I've added any new docs if API/utils methods were added.
- [ ] I have updated the existing documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by michamos** [comment]
if I understood correctly what alembic was about, couldn't you write an alembic script for that?

**Comment by jacquerie** [comment]
> if I understood correctly what alembic was about, couldn't you write an alembic script for that?

True, although (AFAIK) `alembic` is typically used for SQL schema migrations (e.g. adding or removing tables or columns) rather than data migrations.

This also requires a release of `invenio-collections`, otherwise this migration would have no base commit (since the alembic migrations of `invenio-collections` are still in an unreleased commit).

**Comment by jacquerie** [comment]
Blocked by https://github.com/inveniosoftware/invenio-collections/pull/82.

**Comment by jacquerie** [comment]
> Blocked by inveniosoftware/invenio-collections#82.

Not anymore, because commit 7a2e3a8 made searching on this field case-insensitive.

**Pull request merged**
