### PR TITLE
theme: fix kek links macro

### LINKED ISSUE #2926: theme: KEK links are broken
## Expected Behavior

KEK changed their URLs some time ago, see https://github.com/inspirehep/inspire/pull/226 so we should use the new URLs to link to KEK preprints.

## Current Behavior

We are still using the old URLs.

### PR DESCRIPTION
**Pull request by Dinika**
Signed-off-by: Dinika <dinika.saxena@cern.ch>

## Related Issue
closes #2926 

## Checklist:

- [ ] I have all the information that I need (if not, move to `RFC` and look for it).
- [x] I linked the related issue(s) in the corresponding commit logs.
- [x] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [x] My code follows the code style of this project.
- [ ] I've added any new docs if API/utils methods were added.
- [ ] I have updated the existing documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Dinika** [comment]
I can't find a record that has a kEK external identifier, so I'm unable to check this code thoroughly.

**Comment by jacquerie** [comment]
> I can't find a record that has a kEK external identifier, so I'm unable to check this code thoroughly.

There you go: https://inspirehep.net/record/770711

**Comment by Dinika** [comment]
> There you go: https://inspirehep.net/record/770711

Thanks! The code works for this one.

**Comment by jacquerie** [comment]
> Thanks! The code works for this one.

I trust your word on this, but it's always a good idea to prove it with a test. Sadly the architecture of the UI code is inherently not testable, so we will have to skip it for now, and open a "Technical Debt" issue to do what @michamos suggested at some point: find a way to pull these macros out of Jinja and into testable Python code, e.g. in a "wrapper" class.

**Pull request merged**
