### PR TITLE
utils: fixes publi_info in output formats

### LINKED ISSUE #697: Fix publi_info display in latex.
Currently due to some model changes we did, we caused a problem in publi_info.
screen shot 2016-01-11 at 13 28 19

### PR DESCRIPTION
**Pull request by ioannistsanaktsidis**
* Closes #697.

Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

### CODE REVIEW

**Comment by jmartinm** [comment]
Is it possible to add a test as mentioned by @kaplun ?

**Comment by ioannistsanaktsidis** [comment]
There is already a test for this functionality. 
```
self.sample_latex_eu = {
            'citation_key': 'Aad:2015wqa',
            'author': 'G.~Aad',
            'title': '\nSearch for supersymmetry in events containing a same-flavour opposite-sign dilepton pair, jets, and large missing transverse momentum in $\sqrt{s}=8$ TeV $pp$ collisions with the ATLAS detector\n',
            'publi_info': ['Eur.\ Phys.\ J.\ C {\\bf 75} (2015) 7,  318', '[Eur.\ Phys.\ J.\ C {\\bf 75} (2015) 10,  463]'],
            'arxiv': 'arXiv:1503.03290 [hep-ex]',
            'report_number': '',
            'SLACcitation': '%%CITATION = ARXIV:1503.03290;%%',

        }
```
Should I add the case that was failing
?

**Comment by jmartinm** [comment]
Yes, the idea would be to add a test that fails before applying this commit (the expected scenario) and then passes after applying this commit.

**Comment by ioannistsanaktsidis** [comment]
Just added the tests.

**Pull request merged**
