### PR TITLE
facets: adds clear filters button

### LINKED ISSUE #573: Facets reset
I think a quick way to reset facets (and hence start a new search session) is missing.

E.g. imagine I am deep into certain facets but then I'd like to start a new search anew. Currently I would need either to go to the homepage or to unclick the facets one by one.

### PR DESCRIPTION
**Pull request by ioannistsanaktsidis**
* Closes #573.

Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

### CODE REVIEW

**Comment by jmartinm** [comment]
Can you add a screenshot?

**Comment by ioannistsanaktsidis** [comment]
screen shot 2015-12-08 at 10 32 40

**Comment by jmartinm** [comment]
It would be nice to have a closer to design to the one proposed in https://github.com/inspirehep/inspire-next/issues/573

Can you have a look and check with @eamonnmag if you need help?

See as well the text 

```
23 of 300 publications coincide with the filters you selected. [ Clear Filters ]
```

**Comment by salmele** [comment]
> 23 of 300 publications coincide with the filters you selected.

Selected 23 of 300

?

**Comment by eamonnmag** [comment]
Selected has a different meaning. Since selection happens also for download of the bibtex for example. So we should avoid that.

**Comment by nikpap** [comment]
Filtered 23 of 300?

I think `coincide` might not be the simplest term to use.

**Comment by eamonnmag** [comment]
screen shot 2015-12-08 at 4 31 56 p m

**Comment by salmele** [comment]
"Match your filters"
"Match the filters"

**Comment by ioannistsanaktsidis** [comment]
@jmartinm this one I guess is ready, should I rebase with latest master, test and then we can merge it ?

**Pull request merged**
