### PR TITLE
migrator: upgrades removal

### PR DESCRIPTION
**Pull request by jalavik**
* Removes legacy upgrade scripts.

* Updates invenio-workflows signal receiver.

CC @kaplun

### CODE REVIEW

**Comment by jacquerie** [comment]
:tada:

**Comment by jacquerie** [comment]
Sorry for being _that guy_, but can you split the commit in two?

**Comment by jalavik** [comment]
@jacquerie Done!

**Comment by jacquerie** [comment]
Nice! :+1:

Will merge now.

**Pull request merged**
