### PR TITLE
receivers: extract UMR number for affiliation suggester

### PR DESCRIPTION
**Pull request by drjova**
Signed-off-by: Harris Tzovanakis <me@drjova.com>

### CODE REVIEW

**Comment by ammirate** [comment]
Tests in `test_theme_views` are failing, though.

**Comment by drjova** [comment]
This is not related :/ it's something wrong with redis service will check

**Comment by michamos** [comment]
can this be done in a less hackish way? Does this issue only appear with numbers or is it more general if what you're searching for is not the first word of the field?

Honestly, I don't think this warrants special casing UMR. Have you tried changing `preserve_position_increments` instead (see https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-suggesters-completion.html )?

**Comment by ammirate** [comment]
ci test please

**Comment by ammirate** [comment]
ci test please unit

**Pull request merged**
