### PR TITLE
search: create collection search pages

### PR DESCRIPTION
**Pull request by jmartinm**
* Creates a different template for each collection search results page.

* Adapts search view so that a different template is applied depending
  on the collection being searched on (using cc parameter).

Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>

### CODE REVIEW

**Comment by jmartinm** [comment]
At the moment, the same serializer is being used for all collections

```
'application/vnd+inspire.brief+json': (
    'inspirehep.modules.records.serializers'
    ':json_brief_v1_search'
```

This needs to be changed later to have a different one per collection.

Search results templates currently just inherit from `search.html`, later they should overwrite some blocks to have, for example, their own brief format:

```
{%- block search_results %}
    <invenio-search-results
     template="{{ url_for('static', filename='node_modules/inspirehep-search-js/dist/templates/literature/results.html') }}">
    </invenio-search-results>
{%- endblock search_results %}
```

**Comment by jmartinm** [comment]
One view `/search` is at the moment being shared (with different template being rendered depending on `cc` parameter) - https://github.com/jmartinm/inspire-next/blob/collection-search-pages/inspirehep/modules/search/views.py#L41 this seems to be working fine, any other solutions?

**Comment by jmartinm** [comment]
@jalavik @kaplun @jacquerie let me know if it looks ok for you.

**Comment by jalavik** [comment]
Looks good :+1:

**Pull request merged**
