### PR TITLE
831 requirements: pin SQLAlchemy-Continuum==1.3.4

### PR DESCRIPTION
**Pull request by turtle321**

### CODE REVIEW

**Comment by turtle321** [comment]
ci test please

**Comment by david-caro** [comment]
Did you open an issue on the original repo? If so might be nice to reference it in the setup.py with a comment there (so we don't forget why it's there).

**Comment by turtle321** [comment]
I investigated further and reproduced the error, see:
https://its.cern.ch/jira/browse/INSPIR-831

There is an issue open in the original repo for that `VersionConflict` error:
https://github.com/kvesteri/sqlalchemy-continuum/issues/187
I believe this is managed in `invenio-db`.
I'll add a comment in the codebase.

**Comment by david-caro** [comment]
ci merge please

**Pull request merged**
