### PR TITLE
format: HEP detailed abstract

### LINKED ISSUE #866: MathJax and abstract truncation
In record: http://localhost:4000/record/1286320 (https://qa.inspirehep.net/record/1286320), the MathJax formula is broken by the "show abstract" link. (see correct representation at https://inspirehep.net/record/1286320)

This could be mitigated by breaking the abstract at `.` or with some even smarter criteria.

### PR DESCRIPTION
**Pull request by nikpap**
* Resolves abstract truncation error. (closes #866)

Signed-off-by: Nick Papoutsis <admin@nils.gr>

### CODE REVIEW

**Comment by jmartinm** [comment]
By the way, before, the Jinja extension `do` was being used and we removed the usages as we were not sure how to enable the extension again. But we can now enable it again like this https://github.com/inspirehep/inspire-next/pull/908/files#diff-d6327039aeba58b1f251b62ff9a63b92R59 so let me know if it would make the code simpler and I can just merge the small snippet that adds the extension.

**Comment by jmartinm** [comment]
As now the macro will only be used in the detailed page (for brief we will do the same in JavaScript), can you simplify the `abstract` macros and remove the case of brief template? And then the macro can be moved to the detailed macros file.

**Comment by nikpap** [comment]
@jmartinm updated. :shipit:

**Comment by jacquerie** [comment]
Now that #1022 was merged maybe we should merge this. Is this still ready to review, @nikpap?

**Comment by nikpap** [comment]
@eamonnmag @jacquerie this one's indeed ready.

**Comment by eamonnmag** [comment]
I'm in a meeting. @jacquerie, can you check this out if you have time?

**Comment by jacquerie** [comment]
> can you check this out if you have time?

:+1:

**Comment by jacquerie** [comment]
Uhm, not sure this PR is correct: visiting http://localhost:5000/literature/1286320 has "No abstract available for this record.", but this doesn't look right: https://labs.inspirehep.net/record/1286320.

**Comment by jacquerie** [comment]
BTW, this needs a rebase.

**Comment by nikpap** [comment]
@jacquerie Updated and rebased, should now be working as expected. Thanks for noting this issue, it was there before this PR as well! :+1:

**Pull request merged**
