### PR TITLE
citations: production citation syncronization

### PR DESCRIPTION
**Pull request by Panos512**
* Adds citations functionality on labs.
* Adds models for Citations and Citation Log.
* Pulls log from production and populates rnkCITATIONDICT and rnkCITATIONLOG tables.
* Updates records with a new field (references_id) containing the ids of the references.
* Adds test cases for database insertions and record updates.

### CODE REVIEW

**Comment by jalavik** [comment]
Thanks @Panos512. I notice there is a merge commit in this PR. Generally you can avoid these by using `git rebase`. E.g. 

```git
git checkout master
git pull
git checkout citations_api
git rebase -i master     # now "pick" only your own commits in the text buffer
```
Then you should have a clean commit on top of `master` with your 2 commits and no merge commit.

**Comment by Panos512** [comment]
Thanks @jalavik I was trying to get the new version of master. I believe that's why it happened. I will do it the proper way next time

**Comment by kaplun** [comment]
Hi @Panos512, Travis reports that your tests are failing (I think because there are no records in the system?)

**Comment by kaplun** [comment]
It's all green Yay! Be careful: the commit log now is out of sync as it does not mention anymore about the functionality you have implemented :-)

**Comment by Panos512** [comment]
Thanks @kaplun! I am fixing those few things and committing them asap

**Comment by kaplun** [comment]
@Panos512 can you just rebase your branch once more so that I can merge it?

**Comment by jalavik** [comment]
@Panos512 @kaplun The commit log message is not yet perfect.

**Comment by kaplun** [comment]
@jalavik true! Thanks for the heads up.

**Comment by Panos512** [comment]
@kaplun @jalavik I think I fixed it now

**Comment by jalavik** [comment]
@Panos512 Almost! Just remove `WIP` from the first line as this is no longer work-in-progress. Thanks!

**Comment by kaplun** [comment]
eheh, and you are missing the dots at the end of each line :smile: 

But... I have just run `kwalitee check message` against it and it doesn't complain... @jalavik didn't kwalitee complained about such things?

**Comment by Panos512** [comment]
Done! I think everything is ok now

**Pull request merged**
