### PR TITLE
dojson: fix curated_relation

### PR DESCRIPTION
**Pull request by kaplun**
* Fixes porting 100/700 $y into curated_relation flag.

Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
cc @jacenkow

**Comment by kaplun** [comment]
Merging since I know it is passing locally on Docker...

**Comment by jacenkow** [comment]
@kaplun Va bene, sto iniziando il raggruppamento

**Comment by kaplun** [comment]
Bravissimo

**Pull request merged**
