### PR TITLE
WIP deposit: include extra data in stats

### PR DESCRIPTION
**Pull request by pedrogaudencio**

### CODE REVIEW

**Comment by pedrogaudencio** [comment]
@jmartinm, is this ok?

screenshot from 2015-03-04 14 23 37

**Comment by kaplun** [comment]
@jmartinm and this?

**Comment by jmartinm** [comment]
Yes, its valid. I have to look into it.

**Comment by jacquerie** [comment]
This will probably be superseded by @eamonnmag's work design-wise, and it might be hopelessly outdated code-wise. Shall we close?

**Pull request closed without merging**
