### PR TITLE
tests: unit tests for workflows/tasks/submission

### PR DESCRIPTION
**Pull request by jacquerie**
Addresses #1773 

- [x] `add_note_entry`
- [x] `close_ticket`
- [ ] `create_ticket`
- [x] `filter_keywords`
- [x] `prepare_files`
- [x] `prepare_keywords`
- [x] `remove_references`
- [x] `reply_ticket`
- [ ] `submit_rt_ticket`
- [x] `send_robotupload`
- [x] `wait_webcoll`

### CODE REVIEW

**Comment by jacquerie** [comment]
Bugs uncovered while writing these tests:

* Most log calls use `format` instead of what is recommended in #1371.
* Most log calls are not `unicode`-safe. Some of these bugs were already solved in #2199.
* It's unsafe to call `strip` on something that might be `None`: https://github.com/inspirehep/inspire-next/blob/5fdbd8bf4ac6bd984406719b6a3d0c91b0b4cf77/inspirehep/modules/workflows/tasks/submission.py#L158
* It's highly probable that the exception in https://github.com/inspirehep/inspire-next/blob/5fdbd8bf4ac6bd984406719b6a3d0c91b0b4cf77/inspirehep/modules/workflows/tasks/submission.py#L222-L223 is impossible to trigger.

**Comment by jacquerie** [comment]
Design problems encountered while writing these tests:

* This whole thing reeks of spaghetti code: relying on some task writing a certain thing in `extra_data` so that some task at some later point will pick it up is error-prone and is guaranteed to break in the future when tasks are added/deleted/reordered.
* These function have too many responsibilities, which results in too many mocks that have to be applied to them while testing. For example [`reply_ticket`](https://github.com/inspirehep/inspire-next/blob/5fdbd8bf4ac6bd984406719b6a3d0c91b0b4cf77/inspirehep/modules/workflows/tasks/submission.py#L127-L189) contains:
  - some logic to get the `ticket_id` on which it should operate;
  - some logic to figure out if the user actually exists;
  - some logic (with fallbacks) to build the ticket body;
  - some logic to fetch an RT instance;
  - finally, some logic to reply to a ticket.

  Note that all these items also have fallback logic to log and bail out if any of these steps fail, effectively duplicating the number of responsibilities of this function.

**Comment by kaplun** [comment]
> relying on some task writing a certain thing in extra_data so that some task at some later point will pick it up is error-prone and is guaranteed to break in the future when tasks are added/deleted/reordered.

Given the workflow engine we are employing, what better pattern would you propose?

**Comment by jacquerie** [comment]
> Given the workflow engine we are employing, what better pattern would you propose?

Enforce dependencies in code. If task A logically requires task B to be run before it (for example: B is a machine learning algorithm, A persists its results in the record) this must be enforced in code. How? Strong conventions on naming things, ban the use of patterns like `extra_data.get(...)`.

**Comment by kaplun** [comment]
> Strong conventions on naming things, ban the use of patterns like extra_data.get(...).

Actually that makes me think that the object passed around doesn't need to be really a dictionary, so we could pass an actual object with dedicated properties/methods that can then enforce the conventions.

Only issue would be serialization in the DB. But shouldn't be impossible, to just serialize as dictionary and reinstantiate back as full-fledged object.

**Comment by kaplun** [comment]
Or more simply, indeed we can have setters and getters that receive the `obj` as first arguments, allowing for still keeping the `obj` as a simple dict, but hiding the complexity of writing/accessing special  *extra* keys...

**Comment by david-caro** [comment]
> ban the use of patterns like extra_data.get(...)

I'm curious, why do you think that doing that (banning the usage of .get) is enforcing in code dependencies between tasks?

**Comment by jacquerie** [comment]
> I'm curious, why do you think that doing that (banning the usage of .get) is enforcing in code dependencies between tasks?

To avoid failing silently. The problem is in patterns like
```python
foo = extra_data.get('foo')
if foo:
    ...
```
because this is *not* enforcing a dependency on `foo`, so if the task that populates it starts failing tomorrow we are never going to see it. Things should fail loudly and clearly.

**Comment by david-caro** [comment]
That can be easily avoided with `extra_data['foo']` :)

**Comment by jacquerie** [comment]
That was my point!

**Comment by david-caro** [comment]
Sorry, I missed that point XS

**Comment by jacquerie** [comment]
> * It's unsafe to call `strip` on something that might be `None`: https://github.com/inspirehep/inspire-next/blob/5fdbd8bf4ac6bd984406719b6a3d0c91b0b4cf77/inspirehep/modules/workflows/tasks/submission.py#L158

...and in fact: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/822209/

**Comment by jacquerie** [comment]
Victim of https://github.com/inspirehep/inspire-next/issues/2385.

**Pull request merged**
