### PR TITLE
tests: unit tests for literaturesuggest DoJSON

### PR DESCRIPTION
**Pull request by jacquerie**
Another quick coverage win.

### CODE REVIEW

**Comment by jacquerie** [comment]
First commit adds unit tests for the `literaturesuggest` DoJSON rules. Second commit fixes a bug found while writing these tests.

**Comment by jacquerie** [comment]
Ready for review.

**Comment by kaplun** [comment]
I am understanding this tests (although long) are very simple, but still allowed you to spot a bug. Well done. I wonder if they are making it though more rigid our ability to change the data model (in the sense that a small change will now imply fixing several tests as well), but I guess that's a price to pay for stability.

**Comment by jacquerie** [comment]
The biggest benefit of unit tests is evident when refactoring: if you want to ensure that behaviour stays the same, being constrained by what the tests say the code used to do is very beneficial.

If you're reimplementing from scratch, instead, you can probably throw all the unit tests away. Hopefully then you are constrained by your integration tests.

**Comment by jacquerie** [comment]
BTW: this test is similar in spirit to https://github.com/inspirehep/inspire-next/blob/6cf8c2d110833e69b608f7383d305e37a81e202a/tests/test_hep_submission.py, so we can say that this PR addresses #918.

**Comment by kaplun** [comment]
LGBT

**Comment by eamonnmag** [comment]
Are you wearing your pink cardigan again? 💃

**Comment by kaplun** [comment]
:two_women_holding_hands:

**Pull request merged**
