### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by kaplun**
Signed-off-by: Samuele Kaplun samuele.kaplun@cern.ch

### CODE REVIEW

**Comment by jacquerie** [comment]
What did you discover from this? Can we close?

**Comment by kaplun** [comment]
The name of coverage files. I wasn't sure if the combine was doing the right thing. Apparently it does.

**Comment by kaplun** [comment]
Actually: just checked the selenium test:
```
travis_time:end:1c8f648d:start=1476200399447458407,finish=1476200399456708514,duration=9250107
[0Ktravis_fold:end:after_success.1
[0Ktravis_fold:start:after_success.2
[0Ktravis_time:start:03def000
[0K$ ls .coverage*
.coveragerc  .coverage.tests
```
I have here the proof that coverage is not created. I know the reason. Coverage would be created only when stopping gunicorn cleanly (e.g. sending a SIGTERM).

What is the best way to do this in Docker within Travis?

**Comment by kaplun** [comment]
Mmh. Shit I was already doing that :(

**Pull request closed without merging**
