### PR TITLE
WIP Impact graph api invenio3 js

### PR DESCRIPTION
**Pull request by jmartinm**

### CODE REVIEW

**Comment by jacquerie** [comment]
Duplicate of #1046?

**Comment by jmartinm** [comment]
> Duplicate of #1046?

Depends on that PR. There is an extra commit here that adds all the JS functionality to use the API and visualize the impact graph. Still WIP.

**Comment by jmartinm** [comment]
Something like:

screen shot 2016-04-15 at 5 32 52 pm

**Comment by jacquerie** [comment]
> There is an extra commit here that adds all the JS functionality to use the API and visualize the impact graph.

That's why I was asking, that commit is in #1046 as well : )

**Comment by jmartinm** [comment]
> That's why I was asking, that commit is in #1046 as well : )

Whops. Removed.

**Comment by bing13** [comment]
at some point, would like to hear a description of what that graph is. sorry if I missed it elsewhere.

**Comment by jmartinm** [comment]
@bing13 

[EGauthorGuidelines-eurovis16-short.pdf](https://github.com/inspirehep/inspire-next/files/229470/EGauthorGuidelines-eurovis16-short.pdf)

**Comment by bing13** [comment]
ah! thanks, @jmartinm  .  the shape was so odd, I didn't recognize it as an impact graph. 

nice paper!

B

**Pull request closed without merging**
