### PR TITLE
authors: ports author new to invenio3

### PR DESCRIPTION
**Pull request by ioannistsanaktsidis**
Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

### CODE REVIEW

**Comment by ioannistsanaktsidis** [comment]
@jmartinm I thing that we can check this one and merge it, and then from here @jalavik  takes care the holdingpen staff.

**Comment by jalavik** [comment]
@ioannistsanaktsidis Can you rebase with `invenio3` and fix any conflicts?

**Comment by ioannistsanaktsidis** [comment]
Sure!

**Comment by ioannistsanaktsidis** [comment]
@jalavik  Updated!

**Comment by jalavik** [comment]
@ioannistsanaktsidis Can you also apply on top these recent patches from `master`:

https://github.com/inspirehep/inspire-next/commit/82d77f47c9a5ee17d56768d819453843582fe437
https://github.com/inspirehep/inspire-next/commit/aad9716838a30949c1f99bc3c66558b34832757e

**Comment by ioannistsanaktsidis** [comment]
@jalavik done!

**Comment by jalavik** [comment]
@ioannistsanaktsidis Thanks! I will do a test locally and merge if all ok.

**Comment by ioannistsanaktsidis** [comment]
:+1:

**Pull request merged**
