### PR TITLE
scripts: temporary fix for clean_assets

### PR DESCRIPTION
**Pull request by jalavik**
cc @jacquerie

### CODE REVIEW

**Comment by jacquerie** [comment]
:+1:

**Comment by jmartinm** [comment]
LGTM, the issue should be fixed soon though. @drjova told me this morning the problem is that `.gitignore` was being checked when building so `dist/` folder was ignored - https://docs.travis-ci.com/user/deployment/heroku/#Deploy-Strategy

**Comment by jmartinm** [comment]
https://github.com/inveniosoftware/invenio-search-js/pull/55

**Comment by jalavik** [comment]
Reinstalling invenio-search-js now makes this PR obsolete.

**Pull request closed without merging**
